using CDTKPMNC_STK_BE.Models;
using CDTKPMNC_STK_BE.Utilities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System.Reflection.Metadata;

namespace CDTKPMNC_STK_BE.DataAccess.DbConfigurations
{

        public class SeedWard : IEntityTypeConfiguration<AddressWard>
        {
            public void Configure(EntityTypeBuilder<AddressWard> builder)
            {
                builder.HasData(
                    new AddressWard { Id = "26734", Name = "Tân Định", FullName = "Phường Tân Định", NameEN = "Tan Dinh", FullNameEN = "Tan Dinh Ward", DistrictId = "760", ProvinceId = "79" },
                    new AddressWard { Id = "26737", Name = "Đa Kao", FullName = "Phường Đa Kao", NameEN = "Da Kao", FullNameEN = "Da Kao Ward", DistrictId = "760", ProvinceId = "79" },
                    new AddressWard { Id = "26740", Name = "Bến Nghé", FullName = "Phường Bến Nghé", NameEN = "Ben Nghe", FullNameEN = "Ben Nghe Ward", DistrictId = "760", ProvinceId = "79" },
                    new AddressWard { Id = "26743", Name = "Bến Thành", FullName = "Phường Bến Thành", NameEN = "Ben Thanh", FullNameEN = "Ben Thanh Ward", DistrictId = "760", ProvinceId = "79" },
                    new AddressWard { Id = "26746", Name = "Nguyễn Thái Bình", FullName = "Phường Nguyễn Thái Bình", NameEN = "Nguyen Thai Binh", FullNameEN = "Nguyen Thai Binh Ward", DistrictId = "760", ProvinceId = "79" },
                    new AddressWard { Id = "26749", Name = "Phạm Ngũ Lão", FullName = "Phường Phạm Ngũ Lão", NameEN = "Pham Ngu Lao", FullNameEN = "Pham Ngu Lao Ward", DistrictId = "760", ProvinceId = "79" },
                    new AddressWard { Id = "26752", Name = "Cầu Ông Lãnh", FullName = "Phường Cầu Ông Lãnh", NameEN = "Cau Ong Lanh", FullNameEN = "Cau Ong Lanh Ward", DistrictId = "760", ProvinceId = "79" },
                    new AddressWard { Id = "26755", Name = "Cô Giang", FullName = "Phường Cô Giang", NameEN = "Co Giang", FullNameEN = "Co Giang Ward", DistrictId = "760", ProvinceId = "79" },
                    new AddressWard { Id = "26758", Name = "Nguyễn Cư Trinh", FullName = "Phường Nguyễn Cư Trinh", NameEN = "Nguyen Cu Trinh", FullNameEN = "Nguyen Cu Trinh Ward", DistrictId = "760", ProvinceId = "79" },
                    new AddressWard { Id = "26761", Name = "Cầu Kho", FullName = "Phường Cầu Kho", NameEN = "Cau Kho", FullNameEN = "Cau Kho Ward", DistrictId = "760", ProvinceId = "79" },
                    new AddressWard { Id = "26764", Name = "Thạnh Xuân", FullName = "Phường Thạnh Xuân", NameEN = "Thanh Xuan", FullNameEN = "Thanh Xuan Ward", DistrictId = "761", ProvinceId = "79" },
                    new AddressWard { Id = "26767", Name = "Thạnh Lộc", FullName = "Phường Thạnh Lộc", NameEN = "Thanh Loc", FullNameEN = "Thanh Loc Ward", DistrictId = "761", ProvinceId = "79" },
                    new AddressWard { Id = "26770", Name = "Hiệp Thành", FullName = "Phường Hiệp Thành", NameEN = "Hiep Thanh", FullNameEN = "Hiep Thanh Ward", DistrictId = "761", ProvinceId = "79" },
                    new AddressWard { Id = "26773", Name = "Thới An", FullName = "Phường Thới An", NameEN = "Thoi An", FullNameEN = "Thoi An Ward", DistrictId = "761", ProvinceId = "79" },
                    new AddressWard { Id = "26776", Name = "Tân Chánh Hiệp", FullName = "Phường Tân Chánh Hiệp", NameEN = "Tan Chanh Hiep", FullNameEN = "Tan Chanh Hiep Ward", DistrictId = "761", ProvinceId = "79" },
                    new AddressWard { Id = "26779", Name = "An Phú Đông", FullName = "Phường An Phú Đông", NameEN = "An Phu Dong", FullNameEN = "An Phu Dong Ward", DistrictId = "761", ProvinceId = "79" },
                    new AddressWard { Id = "26782", Name = "Tân Thới Hiệp", FullName = "Phường Tân Thới Hiệp", NameEN = "Tan Thoi Hiep", FullNameEN = "Tan Thoi Hiep Ward", DistrictId = "761", ProvinceId = "79" },
                    new AddressWard { Id = "26785", Name = "Trung Mỹ Tây", FullName = "Phường Trung Mỹ Tây", NameEN = "Trung My Tay", FullNameEN = "Trung My Tay Ward", DistrictId = "761", ProvinceId = "79" },
                    new AddressWard { Id = "26787", Name = "Tân Hưng Thuận", FullName = "Phường Tân Hưng Thuận", NameEN = "Tan Hung Thuan", FullNameEN = "Tan Hung Thuan Ward", DistrictId = "761", ProvinceId = "79" },
                    new AddressWard { Id = "26788", Name = "Đông Hưng Thuận", FullName = "Phường Đông Hưng Thuận", NameEN = "Dong Hung Thuan", FullNameEN = "Dong Hung Thuan Ward", DistrictId = "761", ProvinceId = "79" },
                    new AddressWard { Id = "26791", Name = "Tân Thới Nhất", FullName = "Phường Tân Thới Nhất", NameEN = "Tan Thoi Nhat", FullNameEN = "Tan Thoi Nhat Ward", DistrictId = "761", ProvinceId = "79" },
                    new AddressWard { Id = "26869", Name = "15", FullName = "Phường 15", NameEN = "15", FullNameEN = "Ward 15", DistrictId = "764", ProvinceId = "79" },
                    new AddressWard { Id = "26872", Name = "13", FullName = "Phường 13", NameEN = "13", FullNameEN = "Ward 13", DistrictId = "764", ProvinceId = "79" },
                    new AddressWard { Id = "26875", Name = "17", FullName = "Phường 17", NameEN = "17", FullNameEN = "Ward 17", DistrictId = "764", ProvinceId = "79" },
                    new AddressWard { Id = "26876", Name = "6", FullName = "Phường 6", NameEN = "6", FullNameEN = "Ward 6", DistrictId = "764", ProvinceId = "79" },
                    new AddressWard { Id = "26878", Name = "16", FullName = "Phường 16", NameEN = "16", FullNameEN = "Ward 16", DistrictId = "764", ProvinceId = "79" },
                    new AddressWard { Id = "26881", Name = "12", FullName = "Phường 12", NameEN = "12", FullNameEN = "Ward 12", DistrictId = "764", ProvinceId = "79" },
                    new AddressWard { Id = "26882", Name = "14", FullName = "Phường 14", NameEN = "14", FullNameEN = "Ward 14", DistrictId = "764", ProvinceId = "79" },
                    new AddressWard { Id = "26884", Name = "10", FullName = "Phường 10", NameEN = "10", FullNameEN = "Ward 10", DistrictId = "764", ProvinceId = "79" },
                    new AddressWard { Id = "26887", Name = "05", FullName = "Phường 05", NameEN = "05", FullNameEN = "Ward 05", DistrictId = "764", ProvinceId = "79" },
                    new AddressWard { Id = "26890", Name = "07", FullName = "Phường 07", NameEN = "07", FullNameEN = "Ward 07", DistrictId = "764", ProvinceId = "79" },
                    new AddressWard { Id = "26893", Name = "04", FullName = "Phường 04", NameEN = "04", FullNameEN = "Ward 04", DistrictId = "764", ProvinceId = "79" },
                    new AddressWard { Id = "26896", Name = "01", FullName = "Phường 01", NameEN = "01", FullNameEN = "Ward 01", DistrictId = "764", ProvinceId = "79" },
                    new AddressWard { Id = "26897", Name = "9", FullName = "Phường 9", NameEN = "9", FullNameEN = "Ward 9", DistrictId = "764", ProvinceId = "79" },
                    new AddressWard { Id = "26898", Name = "8", FullName = "Phường 8", NameEN = "8", FullNameEN = "Ward 8", DistrictId = "764", ProvinceId = "79" },
                    new AddressWard { Id = "26899", Name = "11", FullName = "Phường 11", NameEN = "11", FullNameEN = "Ward 11", DistrictId = "764", ProvinceId = "79" },
                    new AddressWard { Id = "26902", Name = "03", FullName = "Phường 03", NameEN = "03", FullNameEN = "Ward 03", DistrictId = "764", ProvinceId = "79" },
                    new AddressWard { Id = "26905", Name = "13", FullName = "Phường 13", NameEN = "13", FullNameEN = "Ward 13", DistrictId = "765", ProvinceId = "79" },
                    new AddressWard { Id = "26908", Name = "11", FullName = "Phường 11", NameEN = "11", FullNameEN = "Ward 11", DistrictId = "765", ProvinceId = "79" },
                    new AddressWard { Id = "26911", Name = "27", FullName = "Phường 27", NameEN = "27", FullNameEN = "Ward 27", DistrictId = "765", ProvinceId = "79" },
                    new AddressWard { Id = "26914", Name = "26", FullName = "Phường 26", NameEN = "26", FullNameEN = "Ward 26", DistrictId = "765", ProvinceId = "79" },
                    new AddressWard { Id = "26917", Name = "12", FullName = "Phường 12", NameEN = "12", FullNameEN = "Ward 12", DistrictId = "765", ProvinceId = "79" },
                    new AddressWard { Id = "26920", Name = "25", FullName = "Phường 25", NameEN = "25", FullNameEN = "Ward 25", DistrictId = "765", ProvinceId = "79" },
                    new AddressWard { Id = "26923", Name = "05", FullName = "Phường 05", NameEN = "05", FullNameEN = "Ward 05", DistrictId = "765", ProvinceId = "79" },
                    new AddressWard { Id = "26926", Name = "07", FullName = "Phường 07", NameEN = "07", FullNameEN = "Ward 07", DistrictId = "765", ProvinceId = "79" },
                    new AddressWard { Id = "26929", Name = "24", FullName = "Phường 24", NameEN = "24", FullNameEN = "Ward 24", DistrictId = "765", ProvinceId = "79" },
                    new AddressWard { Id = "26932", Name = "06", FullName = "Phường 06", NameEN = "06", FullNameEN = "Ward 06", DistrictId = "765", ProvinceId = "79" },
                    new AddressWard { Id = "26935", Name = "14", FullName = "Phường 14", NameEN = "14", FullNameEN = "Ward 14", DistrictId = "765", ProvinceId = "79" },
                    new AddressWard { Id = "26938", Name = "15", FullName = "Phường 15", NameEN = "15", FullNameEN = "Ward 15", DistrictId = "765", ProvinceId = "79" },
                    new AddressWard { Id = "26941", Name = "02", FullName = "Phường 02", NameEN = "02", FullNameEN = "Ward 02", DistrictId = "765", ProvinceId = "79" },
                    new AddressWard { Id = "26944", Name = "01", FullName = "Phường 01", NameEN = "01", FullNameEN = "Ward 01", DistrictId = "765", ProvinceId = "79" },
                    new AddressWard { Id = "26947", Name = "03", FullName = "Phường 03", NameEN = "03", FullNameEN = "Ward 03", DistrictId = "765", ProvinceId = "79" },
                    new AddressWard { Id = "26950", Name = "17", FullName = "Phường 17", NameEN = "17", FullNameEN = "Ward 17", DistrictId = "765", ProvinceId = "79" },
                    new AddressWard { Id = "26953", Name = "21", FullName = "Phường 21", NameEN = "21", FullNameEN = "Ward 21", DistrictId = "765", ProvinceId = "79" },
                    new AddressWard { Id = "26956", Name = "22", FullName = "Phường 22", NameEN = "22", FullNameEN = "Ward 22", DistrictId = "765", ProvinceId = "79" },
                    new AddressWard { Id = "26959", Name = "19", FullName = "Phường 19", NameEN = "19", FullNameEN = "Ward 19", DistrictId = "765", ProvinceId = "79" },
                    new AddressWard { Id = "26962", Name = "28", FullName = "Phường 28", NameEN = "28", FullNameEN = "Ward 28", DistrictId = "765", ProvinceId = "79" },
                    new AddressWard { Id = "26965", Name = "02", FullName = "Phường 02", NameEN = "02", FullNameEN = "Ward 02", DistrictId = "766", ProvinceId = "79" },
                    new AddressWard { Id = "26968", Name = "04", FullName = "Phường 04", NameEN = "04", FullNameEN = "Ward 04", DistrictId = "766", ProvinceId = "79" },
                    new AddressWard { Id = "26971", Name = "12", FullName = "Phường 12", NameEN = "12", FullNameEN = "Ward 12", DistrictId = "766", ProvinceId = "79" },
                    new AddressWard { Id = "26974", Name = "13", FullName = "Phường 13", NameEN = "13", FullNameEN = "Ward 13", DistrictId = "766", ProvinceId = "79" },
                    new AddressWard { Id = "26977", Name = "01", FullName = "Phường 01", NameEN = "01", FullNameEN = "Ward 01", DistrictId = "766", ProvinceId = "79" },
                    new AddressWard { Id = "26980", Name = "03", FullName = "Phường 03", NameEN = "03", FullNameEN = "Ward 03", DistrictId = "766", ProvinceId = "79" },
                    new AddressWard { Id = "26983", Name = "11", FullName = "Phường 11", NameEN = "11", FullNameEN = "Ward 11", DistrictId = "766", ProvinceId = "79" },
                    new AddressWard { Id = "26986", Name = "07", FullName = "Phường 07", NameEN = "07", FullNameEN = "Ward 07", DistrictId = "766", ProvinceId = "79" },
                    new AddressWard { Id = "26989", Name = "05", FullName = "Phường 05", NameEN = "05", FullNameEN = "Ward 05", DistrictId = "766", ProvinceId = "79" },
                    new AddressWard { Id = "26992", Name = "10", FullName = "Phường 10", NameEN = "10", FullNameEN = "Ward 10", DistrictId = "766", ProvinceId = "79" },
                    new AddressWard { Id = "26995", Name = "06", FullName = "Phường 06", NameEN = "06", FullNameEN = "Ward 06", DistrictId = "766", ProvinceId = "79" },
                    new AddressWard { Id = "26998", Name = "08", FullName = "Phường 08", NameEN = "08", FullNameEN = "Ward 08", DistrictId = "766", ProvinceId = "79" },
                    new AddressWard { Id = "27001", Name = "09", FullName = "Phường 09", NameEN = "09", FullNameEN = "Ward 09", DistrictId = "766", ProvinceId = "79" },
                    new AddressWard { Id = "27004", Name = "14", FullName = "Phường 14", NameEN = "14", FullNameEN = "Ward 14", DistrictId = "766", ProvinceId = "79" },
                    new AddressWard { Id = "27007", Name = "15", FullName = "Phường 15", NameEN = "15", FullNameEN = "Ward 15", DistrictId = "766", ProvinceId = "79" },
                    new AddressWard { Id = "27010", Name = "Tân Sơn Nhì", FullName = "Phường Tân Sơn Nhì", NameEN = "Tan Son Nhi", FullNameEN = "Tan Son Nhi Ward", DistrictId = "767", ProvinceId = "79" },
                    new AddressWard { Id = "27013", Name = "Tây Thạnh", FullName = "Phường Tây Thạnh", NameEN = "Tay Thanh", FullNameEN = "Tay Thanh Ward", DistrictId = "767", ProvinceId = "79" },
                    new AddressWard { Id = "27016", Name = "Sơn Kỳ", FullName = "Phường Sơn Kỳ", NameEN = "Son Ky", FullNameEN = "Son Ky Ward", DistrictId = "767", ProvinceId = "79" },
                    new AddressWard { Id = "27019", Name = "Tân Quý", FullName = "Phường Tân Quý", NameEN = "Tan Quy", FullNameEN = "Tan Quy Ward", DistrictId = "767", ProvinceId = "79" },
                    new AddressWard { Id = "27022", Name = "Tân Thành", FullName = "Phường Tân Thành", NameEN = "Tan Thanh", FullNameEN = "Tan Thanh Ward", DistrictId = "767", ProvinceId = "79" },
                    new AddressWard { Id = "27025", Name = "Phú Thọ Hòa", FullName = "Phường Phú Thọ Hòa", NameEN = "Phu Tho Hoa", FullNameEN = "Phu Tho Hoa Ward", DistrictId = "767", ProvinceId = "79" },
                    new AddressWard { Id = "27028", Name = "Phú Thạnh", FullName = "Phường Phú Thạnh", NameEN = "Phu Thanh", FullNameEN = "Phu Thanh Ward", DistrictId = "767", ProvinceId = "79" },
                    new AddressWard { Id = "27031", Name = "Phú Trung", FullName = "Phường Phú Trung", NameEN = "Phu Trung", FullNameEN = "Phu Trung Ward", DistrictId = "767", ProvinceId = "79" },
                    new AddressWard { Id = "27034", Name = "Hòa Thạnh", FullName = "Phường Hòa Thạnh", NameEN = "Hoa Thanh", FullNameEN = "Hoa Thanh Ward", DistrictId = "767", ProvinceId = "79" },
                    new AddressWard { Id = "27037", Name = "Hiệp Tân", FullName = "Phường Hiệp Tân", NameEN = "Hiep Tan", FullNameEN = "Hiep Tan Ward", DistrictId = "767", ProvinceId = "79" },
                    new AddressWard { Id = "27040", Name = "Tân Thới Hòa", FullName = "Phường Tân Thới Hòa", NameEN = "Tan Thoi Hoa", FullNameEN = "Tan Thoi Hoa Ward", DistrictId = "767", ProvinceId = "79" },
                    new AddressWard { Id = "27043", Name = "04", FullName = "Phường 04", NameEN = "04", FullNameEN = "Ward 04", DistrictId = "768", ProvinceId = "79" },
                    new AddressWard { Id = "27046", Name = "05", FullName = "Phường 05", NameEN = "05", FullNameEN = "Ward 05", DistrictId = "768", ProvinceId = "79" },
                    new AddressWard { Id = "27049", Name = "09", FullName = "Phường 09", NameEN = "09", FullNameEN = "Ward 09", DistrictId = "768", ProvinceId = "79" },
                    new AddressWard { Id = "27052", Name = "07", FullName = "Phường 07", NameEN = "07", FullNameEN = "Ward 07", DistrictId = "768", ProvinceId = "79" },
                    new AddressWard { Id = "27055", Name = "03", FullName = "Phường 03", NameEN = "03", FullNameEN = "Ward 03", DistrictId = "768", ProvinceId = "79" },
                    new AddressWard { Id = "27058", Name = "01", FullName = "Phường 01", NameEN = "01", FullNameEN = "Ward 01", DistrictId = "768", ProvinceId = "79" },
                    new AddressWard { Id = "27061", Name = "02", FullName = "Phường 02", NameEN = "02", FullNameEN = "Ward 02", DistrictId = "768", ProvinceId = "79" },
                    new AddressWard { Id = "27064", Name = "08", FullName = "Phường 08", NameEN = "08", FullNameEN = "Ward 08", DistrictId = "768", ProvinceId = "79" },
                    new AddressWard { Id = "27067", Name = "15", FullName = "Phường 15", NameEN = "15", FullNameEN = "Ward 15", DistrictId = "768", ProvinceId = "79" },
                    new AddressWard { Id = "27070", Name = "10", FullName = "Phường 10", NameEN = "10", FullNameEN = "Ward 10", DistrictId = "768", ProvinceId = "79" },
                    new AddressWard { Id = "27073", Name = "11", FullName = "Phường 11", NameEN = "11", FullNameEN = "Ward 11", DistrictId = "768", ProvinceId = "79" },
                    new AddressWard { Id = "27076", Name = "17", FullName = "Phường 17", NameEN = "17", FullNameEN = "Ward 17", DistrictId = "768", ProvinceId = "79" },
                    new AddressWard { Id = "27085", Name = "13", FullName = "Phường 13", NameEN = "13", FullNameEN = "Ward 13", DistrictId = "768", ProvinceId = "79" },
                    new AddressWard { Id = "26794", Name = "Linh Xuân", FullName = "Phường Linh Xuân", NameEN = "Linh Xuan", FullNameEN = "Linh Xuan Ward", DistrictId = "769", ProvinceId = "79" },
                    new AddressWard { Id = "26797", Name = "Bình Chiểu", FullName = "Phường Bình Chiểu", NameEN = "Binh Chieu", FullNameEN = "Binh Chieu Ward", DistrictId = "769", ProvinceId = "79" },
                    new AddressWard { Id = "26800", Name = "Linh Trung", FullName = "Phường Linh Trung", NameEN = "Linh Trung", FullNameEN = "Linh Trung Ward", DistrictId = "769", ProvinceId = "79" },
                    new AddressWard { Id = "26803", Name = "Tam Bình", FullName = "Phường Tam Bình", NameEN = "Tam Binh", FullNameEN = "Tam Binh Ward", DistrictId = "769", ProvinceId = "79" },
                    new AddressWard { Id = "26806", Name = "Tam Phú", FullName = "Phường Tam Phú", NameEN = "Tam Phu", FullNameEN = "Tam Phu Ward", DistrictId = "769", ProvinceId = "79" },
                    new AddressWard { Id = "26809", Name = "Hiệp Bình Phước", FullName = "Phường Hiệp Bình Phước", NameEN = "Hiep Binh Phuoc", FullNameEN = "Hiep Binh Phuoc Ward", DistrictId = "769", ProvinceId = "79" },
                    new AddressWard { Id = "26812", Name = "Hiệp Bình Chánh", FullName = "Phường Hiệp Bình Chánh", NameEN = "Hiep Binh Chanh", FullNameEN = "Hiep Binh Chanh Ward", DistrictId = "769", ProvinceId = "79" },
                    new AddressWard { Id = "26815", Name = "Linh Chiểu", FullName = "Phường Linh Chiểu", NameEN = "Linh Chieu", FullNameEN = "Linh Chieu Ward", DistrictId = "769", ProvinceId = "79" },
                    new AddressWard { Id = "26818", Name = "Linh Tây", FullName = "Phường Linh Tây", NameEN = "Linh Tay", FullNameEN = "Linh Tay Ward", DistrictId = "769", ProvinceId = "79" },
                    new AddressWard { Id = "26821", Name = "Linh Đông", FullName = "Phường Linh Đông", NameEN = "Linh Dong", FullNameEN = "Linh Dong Ward", DistrictId = "769", ProvinceId = "79" },
                    new AddressWard { Id = "26824", Name = "Bình Thọ", FullName = "Phường Bình Thọ", NameEN = "Binh Tho", FullNameEN = "Binh Tho Ward", DistrictId = "769", ProvinceId = "79" },
                    new AddressWard { Id = "26827", Name = "Trường Thọ", FullName = "Phường Trường Thọ", NameEN = "Truong Tho", FullNameEN = "Truong Tho Ward", DistrictId = "769", ProvinceId = "79" },
                    new AddressWard { Id = "26830", Name = "Long Bình", FullName = "Phường Long Bình", NameEN = "Long Binh", FullNameEN = "Long Binh Ward", DistrictId = "769", ProvinceId = "79" },
                    new AddressWard { Id = "26833", Name = "Long Thạnh Mỹ", FullName = "Phường Long Thạnh Mỹ", NameEN = "Long Thanh My", FullNameEN = "Long Thanh My Ward", DistrictId = "769", ProvinceId = "79" },
                    new AddressWard { Id = "26836", Name = "Tân Phú", FullName = "Phường Tân Phú", NameEN = "Tan Phu", FullNameEN = "Tan Phu Ward", DistrictId = "769", ProvinceId = "79" },
                    new AddressWard { Id = "26839", Name = "Hiệp Phú", FullName = "Phường Hiệp Phú", NameEN = "Hiep Phu", FullNameEN = "Hiep Phu Ward", DistrictId = "769", ProvinceId = "79" },
                    new AddressWard { Id = "26842", Name = "Tăng Nhơn Phú A", FullName = "Phường Tăng Nhơn Phú A", NameEN = "Tang Nhon Phu A", FullNameEN = "Tang Nhon Phu A Ward", DistrictId = "769", ProvinceId = "79" },
                    new AddressWard { Id = "26845", Name = "Tăng Nhơn Phú B", FullName = "Phường Tăng Nhơn Phú B", NameEN = "Tang Nhon Phu B", FullNameEN = "Tang Nhon Phu B Ward", DistrictId = "769", ProvinceId = "79" },
                    new AddressWard { Id = "26848", Name = "Phước Long B", FullName = "Phường Phước Long B", NameEN = "Phuoc Long B", FullNameEN = "Phuoc Long B Ward", DistrictId = "769", ProvinceId = "79" },
                    new AddressWard { Id = "26851", Name = "Phước Long A", FullName = "Phường Phước Long A", NameEN = "Phuoc Long A", FullNameEN = "Phuoc Long A Ward", DistrictId = "769", ProvinceId = "79" },
                    new AddressWard { Id = "26854", Name = "Trường Thạnh", FullName = "Phường Trường Thạnh", NameEN = "Truong Thanh", FullNameEN = "Truong Thanh Ward", DistrictId = "769", ProvinceId = "79" },
                    new AddressWard { Id = "26857", Name = "Long Phước", FullName = "Phường Long Phước", NameEN = "Long Phuoc", FullNameEN = "Long Phuoc Ward", DistrictId = "769", ProvinceId = "79" },
                    new AddressWard { Id = "26860", Name = "Long Trường", FullName = "Phường Long Trường", NameEN = "Long Truong", FullNameEN = "Long Truong Ward", DistrictId = "769", ProvinceId = "79" },
                    new AddressWard { Id = "26863", Name = "Phước Bình", FullName = "Phường Phước Bình", NameEN = "Phuoc Binh", FullNameEN = "Phuoc Binh Ward", DistrictId = "769", ProvinceId = "79" },
                    new AddressWard { Id = "26866", Name = "Phú Hữu", FullName = "Phường Phú Hữu", NameEN = "Phu Huu", FullNameEN = "Phu Huu Ward", DistrictId = "769", ProvinceId = "79" },
                    new AddressWard { Id = "27088", Name = "Thảo Điền", FullName = "Phường Thảo Điền", NameEN = "Thao Dien", FullNameEN = "Thao Dien Ward", DistrictId = "769", ProvinceId = "79" },
                    new AddressWard { Id = "27091", Name = "An Phú", FullName = "Phường An Phú", NameEN = "An Phu", FullNameEN = "An Phu Ward", DistrictId = "769", ProvinceId = "79" },
                    new AddressWard { Id = "27094", Name = "An Khánh", FullName = "Phường An Khánh", NameEN = "An Khanh", FullNameEN = "An Khanh Ward", DistrictId = "769", ProvinceId = "79" },
                    new AddressWard { Id = "27097", Name = "Bình Trưng Đông", FullName = "Phường Bình Trưng Đông", NameEN = "Binh Trung Dong", FullNameEN = "Binh Trung Dong Ward", DistrictId = "769", ProvinceId = "79" },
                    new AddressWard { Id = "27100", Name = "Bình Trưng Tây", FullName = "Phường Bình Trưng Tây", NameEN = "Binh Trung Tay", FullNameEN = "Binh Trung Tay Ward", DistrictId = "769", ProvinceId = "79" },
                    new AddressWard { Id = "27109", Name = "Cát Lái", FullName = "Phường Cát Lái", NameEN = "Cat Lai", FullNameEN = "Cat Lai Ward", DistrictId = "769", ProvinceId = "79" },
                    new AddressWard { Id = "27112", Name = "Thạnh Mỹ Lợi", FullName = "Phường Thạnh Mỹ Lợi", NameEN = "Thanh My Loi", FullNameEN = "Thanh My Loi Ward", DistrictId = "769", ProvinceId = "79" },
                    new AddressWard { Id = "27115", Name = "An Lợi Đông", FullName = "Phường An Lợi Đông", NameEN = "An Loi Dong", FullNameEN = "An Loi Dong Ward", DistrictId = "769", ProvinceId = "79" },
                    new AddressWard { Id = "27118", Name = "Thủ Thiêm", FullName = "Phường Thủ Thiêm", NameEN = "Thu Thiem", FullNameEN = "Thu Thiem Ward", DistrictId = "769", ProvinceId = "79" },
                    new AddressWard { Id = "27127", Name = "14", FullName = "Phường 14", NameEN = "14", FullNameEN = "Ward 14", DistrictId = "770", ProvinceId = "79" },
                    new AddressWard { Id = "27130", Name = "12", FullName = "Phường 12", NameEN = "12", FullNameEN = "Ward 12", DistrictId = "770", ProvinceId = "79" },
                    new AddressWard { Id = "27133", Name = "11", FullName = "Phường 11", NameEN = "11", FullNameEN = "Ward 11", DistrictId = "770", ProvinceId = "79" },
                    new AddressWard { Id = "27136", Name = "13", FullName = "Phường 13", NameEN = "13", FullNameEN = "Ward 13", DistrictId = "770", ProvinceId = "79" },
                    new AddressWard { Id = "27139", Name = "Võ Thị Sáu", FullName = "Phường Võ Thị Sáu", NameEN = "Vo Thi Sau", FullNameEN = "Vo Thi Sau Ward", DistrictId = "770", ProvinceId = "79" },
                    new AddressWard { Id = "27142", Name = "09", FullName = "Phường 09", NameEN = "09", FullNameEN = "Ward 09", DistrictId = "770", ProvinceId = "79" },
                    new AddressWard { Id = "27145", Name = "10", FullName = "Phường 10", NameEN = "10", FullNameEN = "Ward 10", DistrictId = "770", ProvinceId = "79" },
                    new AddressWard { Id = "27148", Name = "04", FullName = "Phường 04", NameEN = "04", FullNameEN = "Ward 04", DistrictId = "770", ProvinceId = "79" },
                    new AddressWard { Id = "27151", Name = "05", FullName = "Phường 05", NameEN = "05", FullNameEN = "Ward 05", DistrictId = "770", ProvinceId = "79" },
                    new AddressWard { Id = "27154", Name = "03", FullName = "Phường 03", NameEN = "03", FullNameEN = "Ward 03", DistrictId = "770", ProvinceId = "79" },
                    new AddressWard { Id = "27157", Name = "02", FullName = "Phường 02", NameEN = "02", FullNameEN = "Ward 02", DistrictId = "770", ProvinceId = "79" },
                    new AddressWard { Id = "27160", Name = "01", FullName = "Phường 01", NameEN = "01", FullNameEN = "Ward 01", DistrictId = "770", ProvinceId = "79" },
                    new AddressWard { Id = "27163", Name = "15", FullName = "Phường 15", NameEN = "15", FullNameEN = "Ward 15", DistrictId = "771", ProvinceId = "79" },
                    new AddressWard { Id = "27166", Name = "13", FullName = "Phường 13", NameEN = "13", FullNameEN = "Ward 13", DistrictId = "771", ProvinceId = "79" },
                    new AddressWard { Id = "27169", Name = "14", FullName = "Phường 14", NameEN = "14", FullNameEN = "Ward 14", DistrictId = "771", ProvinceId = "79" },
                    new AddressWard { Id = "27172", Name = "12", FullName = "Phường 12", NameEN = "12", FullNameEN = "Ward 12", DistrictId = "771", ProvinceId = "79" },
                    new AddressWard { Id = "27175", Name = "11", FullName = "Phường 11", NameEN = "11", FullNameEN = "Ward 11", DistrictId = "771", ProvinceId = "79" },
                    new AddressWard { Id = "27178", Name = "10", FullName = "Phường 10", NameEN = "10", FullNameEN = "Ward 10", DistrictId = "771", ProvinceId = "79" },
                    new AddressWard { Id = "27181", Name = "09", FullName = "Phường 09", NameEN = "09", FullNameEN = "Ward 09", DistrictId = "771", ProvinceId = "79" },
                    new AddressWard { Id = "27184", Name = "01", FullName = "Phường 01", NameEN = "01", FullNameEN = "Ward 01", DistrictId = "771", ProvinceId = "79" },
                    new AddressWard { Id = "27187", Name = "08", FullName = "Phường 08", NameEN = "08", FullNameEN = "Ward 08", DistrictId = "771", ProvinceId = "79" },
                    new AddressWard { Id = "27190", Name = "02", FullName = "Phường 02", NameEN = "02", FullNameEN = "Ward 02", DistrictId = "771", ProvinceId = "79" },
                    new AddressWard { Id = "27193", Name = "04", FullName = "Phường 04", NameEN = "04", FullNameEN = "Ward 04", DistrictId = "771", ProvinceId = "79" },
                    new AddressWard { Id = "27196", Name = "07", FullName = "Phường 07", NameEN = "07", FullNameEN = "Ward 07", DistrictId = "771", ProvinceId = "79" },
                    new AddressWard { Id = "27199", Name = "05", FullName = "Phường 05", NameEN = "05", FullNameEN = "Ward 05", DistrictId = "771", ProvinceId = "79" },
                    new AddressWard { Id = "27202", Name = "06", FullName = "Phường 06", NameEN = "06", FullNameEN = "Ward 06", DistrictId = "771", ProvinceId = "79" },
                    new AddressWard { Id = "27208", Name = "15", FullName = "Phường 15", NameEN = "15", FullNameEN = "Ward 15", DistrictId = "772", ProvinceId = "79" },
                    new AddressWard { Id = "27211", Name = "05", FullName = "Phường 05", NameEN = "05", FullNameEN = "Ward 05", DistrictId = "772", ProvinceId = "79" },
                    new AddressWard { Id = "27214", Name = "14", FullName = "Phường 14", NameEN = "14", FullNameEN = "Ward 14", DistrictId = "772", ProvinceId = "79" },
                    new AddressWard { Id = "27217", Name = "11", FullName = "Phường 11", NameEN = "11", FullNameEN = "Ward 11", DistrictId = "772", ProvinceId = "79" },
                    new AddressWard { Id = "27220", Name = "03", FullName = "Phường 03", NameEN = "03", FullNameEN = "Ward 03", DistrictId = "772", ProvinceId = "79" },
                    new AddressWard { Id = "27223", Name = "10", FullName = "Phường 10", NameEN = "10", FullNameEN = "Ward 10", DistrictId = "772", ProvinceId = "79" },
                    new AddressWard { Id = "27226", Name = "13", FullName = "Phường 13", NameEN = "13", FullNameEN = "Ward 13", DistrictId = "772", ProvinceId = "79" },
                    new AddressWard { Id = "27229", Name = "08", FullName = "Phường 08", NameEN = "08", FullNameEN = "Ward 08", DistrictId = "772", ProvinceId = "79" },
                    new AddressWard { Id = "27232", Name = "09", FullName = "Phường 09", NameEN = "09", FullNameEN = "Ward 09", DistrictId = "772", ProvinceId = "79" },
                    new AddressWard { Id = "27235", Name = "12", FullName = "Phường 12", NameEN = "12", FullNameEN = "Ward 12", DistrictId = "772", ProvinceId = "79" },
                    new AddressWard { Id = "27238", Name = "07", FullName = "Phường 07", NameEN = "07", FullNameEN = "Ward 07", DistrictId = "772", ProvinceId = "79" },
                    new AddressWard { Id = "27241", Name = "06", FullName = "Phường 06", NameEN = "06", FullNameEN = "Ward 06", DistrictId = "772", ProvinceId = "79" },
                    new AddressWard { Id = "27244", Name = "04", FullName = "Phường 04", NameEN = "04", FullNameEN = "Ward 04", DistrictId = "772", ProvinceId = "79" },
                    new AddressWard { Id = "27247", Name = "01", FullName = "Phường 01", NameEN = "01", FullNameEN = "Ward 01", DistrictId = "772", ProvinceId = "79" },
                    new AddressWard { Id = "27250", Name = "02", FullName = "Phường 02", NameEN = "02", FullNameEN = "Ward 02", DistrictId = "772", ProvinceId = "79" },
                    new AddressWard { Id = "27253", Name = "16", FullName = "Phường 16", NameEN = "16", FullNameEN = "Ward 16", DistrictId = "772", ProvinceId = "79" },
                    new AddressWard { Id = "27259", Name = "13", FullName = "Phường 13", NameEN = "13", FullNameEN = "Ward 13", DistrictId = "773", ProvinceId = "79" },
                    new AddressWard { Id = "27262", Name = "09", FullName = "Phường 09", NameEN = "09", FullNameEN = "Ward 09", DistrictId = "773", ProvinceId = "79" },
                    new AddressWard { Id = "27265", Name = "06", FullName = "Phường 06", NameEN = "06", FullNameEN = "Ward 06", DistrictId = "773", ProvinceId = "79" },
                    new AddressWard { Id = "27268", Name = "08", FullName = "Phường 08", NameEN = "08", FullNameEN = "Ward 08", DistrictId = "773", ProvinceId = "79" },
                    new AddressWard { Id = "27271", Name = "10", FullName = "Phường 10", NameEN = "10", FullNameEN = "Ward 10", DistrictId = "773", ProvinceId = "79" },
                    new AddressWard { Id = "27277", Name = "18", FullName = "Phường 18", NameEN = "18", FullNameEN = "Ward 18", DistrictId = "773", ProvinceId = "79" },
                    new AddressWard { Id = "27280", Name = "14", FullName = "Phường 14", NameEN = "14", FullNameEN = "Ward 14", DistrictId = "773", ProvinceId = "79" },
                    new AddressWard { Id = "27283", Name = "04", FullName = "Phường 04", NameEN = "04", FullNameEN = "Ward 04", DistrictId = "773", ProvinceId = "79" },
                    new AddressWard { Id = "27286", Name = "03", FullName = "Phường 03", NameEN = "03", FullNameEN = "Ward 03", DistrictId = "773", ProvinceId = "79" },
                    new AddressWard { Id = "27289", Name = "16", FullName = "Phường 16", NameEN = "16", FullNameEN = "Ward 16", DistrictId = "773", ProvinceId = "79" },
                    new AddressWard { Id = "27292", Name = "02", FullName = "Phường 02", NameEN = "02", FullNameEN = "Ward 02", DistrictId = "773", ProvinceId = "79" },
                    new AddressWard { Id = "27295", Name = "15", FullName = "Phường 15", NameEN = "15", FullNameEN = "Ward 15", DistrictId = "773", ProvinceId = "79" },
                    new AddressWard { Id = "27298", Name = "01", FullName = "Phường 01", NameEN = "01", FullNameEN = "Ward 01", DistrictId = "773", ProvinceId = "79" },
                    new AddressWard { Id = "27301", Name = "04", FullName = "Phường 04", NameEN = "04", FullNameEN = "Ward 04", DistrictId = "774", ProvinceId = "79" },
                    new AddressWard { Id = "27304", Name = "09", FullName = "Phường 09", NameEN = "09", FullNameEN = "Ward 09", DistrictId = "774", ProvinceId = "79" },
                    new AddressWard { Id = "27307", Name = "03", FullName = "Phường 03", NameEN = "03", FullNameEN = "Ward 03", DistrictId = "774", ProvinceId = "79" },
                    new AddressWard { Id = "27310", Name = "12", FullName = "Phường 12", NameEN = "12", FullNameEN = "Ward 12", DistrictId = "774", ProvinceId = "79" },
                    new AddressWard { Id = "27313", Name = "02", FullName = "Phường 02", NameEN = "02", FullNameEN = "Ward 02", DistrictId = "774", ProvinceId = "79" },
                    new AddressWard { Id = "27316", Name = "08", FullName = "Phường 08", NameEN = "08", FullNameEN = "Ward 08", DistrictId = "774", ProvinceId = "79" },
                    new AddressWard { Id = "27322", Name = "07", FullName = "Phường 07", NameEN = "07", FullNameEN = "Ward 07", DistrictId = "774", ProvinceId = "79" },
                    new AddressWard { Id = "27325", Name = "01", FullName = "Phường 01", NameEN = "01", FullNameEN = "Ward 01", DistrictId = "774", ProvinceId = "79" },
                    new AddressWard { Id = "27328", Name = "11", FullName = "Phường 11", NameEN = "11", FullNameEN = "Ward 11", DistrictId = "774", ProvinceId = "79" },
                    new AddressWard { Id = "27331", Name = "14", FullName = "Phường 14", NameEN = "14", FullNameEN = "Ward 14", DistrictId = "774", ProvinceId = "79" },
                    new AddressWard { Id = "27334", Name = "05", FullName = "Phường 05", NameEN = "05", FullNameEN = "Ward 05", DistrictId = "774", ProvinceId = "79" },
                    new AddressWard { Id = "27337", Name = "06", FullName = "Phường 06", NameEN = "06", FullNameEN = "Ward 06", DistrictId = "774", ProvinceId = "79" },
                    new AddressWard { Id = "27340", Name = "10", FullName = "Phường 10", NameEN = "10", FullNameEN = "Ward 10", DistrictId = "774", ProvinceId = "79" },
                    new AddressWard { Id = "27343", Name = "13", FullName = "Phường 13", NameEN = "13", FullNameEN = "Ward 13", DistrictId = "774", ProvinceId = "79" },
                    new AddressWard { Id = "27346", Name = "14", FullName = "Phường 14", NameEN = "14", FullNameEN = "Ward 14", DistrictId = "775", ProvinceId = "79" },
                    new AddressWard { Id = "27349", Name = "13", FullName = "Phường 13", NameEN = "13", FullNameEN = "Ward 13", DistrictId = "775", ProvinceId = "79" },
                    new AddressWard { Id = "27352", Name = "09", FullName = "Phường 09", NameEN = "09", FullNameEN = "Ward 09", DistrictId = "775", ProvinceId = "79" },
                    new AddressWard { Id = "27355", Name = "06", FullName = "Phường 06", NameEN = "06", FullNameEN = "Ward 06", DistrictId = "775", ProvinceId = "79" },
                    new AddressWard { Id = "27358", Name = "12", FullName = "Phường 12", NameEN = "12", FullNameEN = "Ward 12", DistrictId = "775", ProvinceId = "79" },
                    new AddressWard { Id = "27361", Name = "05", FullName = "Phường 05", NameEN = "05", FullNameEN = "Ward 05", DistrictId = "775", ProvinceId = "79" },
                    new AddressWard { Id = "27364", Name = "11", FullName = "Phường 11", NameEN = "11", FullNameEN = "Ward 11", DistrictId = "775", ProvinceId = "79" },
                    new AddressWard { Id = "27367", Name = "02", FullName = "Phường 02", NameEN = "02", FullNameEN = "Ward 02", DistrictId = "775", ProvinceId = "79" },
                    new AddressWard { Id = "27370", Name = "01", FullName = "Phường 01", NameEN = "01", FullNameEN = "Ward 01", DistrictId = "775", ProvinceId = "79" },
                    new AddressWard { Id = "27373", Name = "04", FullName = "Phường 04", NameEN = "04", FullNameEN = "Ward 04", DistrictId = "775", ProvinceId = "79" },
                    new AddressWard { Id = "27376", Name = "08", FullName = "Phường 08", NameEN = "08", FullNameEN = "Ward 08", DistrictId = "775", ProvinceId = "79" },
                    new AddressWard { Id = "27379", Name = "03", FullName = "Phường 03", NameEN = "03", FullNameEN = "Ward 03", DistrictId = "775", ProvinceId = "79" },
                    new AddressWard { Id = "27382", Name = "07", FullName = "Phường 07", NameEN = "07", FullNameEN = "Ward 07", DistrictId = "775", ProvinceId = "79" },
                    new AddressWard { Id = "27385", Name = "10", FullName = "Phường 10", NameEN = "10", FullNameEN = "Ward 10", DistrictId = "775", ProvinceId = "79" },
                    new AddressWard { Id = "27388", Name = "08", FullName = "Phường 08", NameEN = "08", FullNameEN = "Ward 08", DistrictId = "776", ProvinceId = "79" },
                    new AddressWard { Id = "27391", Name = "02", FullName = "Phường 02", NameEN = "02", FullNameEN = "Ward 02", DistrictId = "776", ProvinceId = "79" },
                    new AddressWard { Id = "27394", Name = "01", FullName = "Phường 01", NameEN = "01", FullNameEN = "Ward 01", DistrictId = "776", ProvinceId = "79" },
                    new AddressWard { Id = "27397", Name = "03", FullName = "Phường 03", NameEN = "03", FullNameEN = "Ward 03", DistrictId = "776", ProvinceId = "79" },
                    new AddressWard { Id = "27400", Name = "11", FullName = "Phường 11", NameEN = "11", FullNameEN = "Ward 11", DistrictId = "776", ProvinceId = "79" },
                    new AddressWard { Id = "27403", Name = "09", FullName = "Phường 09", NameEN = "09", FullNameEN = "Ward 09", DistrictId = "776", ProvinceId = "79" },
                    new AddressWard { Id = "27406", Name = "10", FullName = "Phường 10", NameEN = "10", FullNameEN = "Ward 10", DistrictId = "776", ProvinceId = "79" },
                    new AddressWard { Id = "27409", Name = "04", FullName = "Phường 04", NameEN = "04", FullNameEN = "Ward 04", DistrictId = "776", ProvinceId = "79" },
                    new AddressWard { Id = "27412", Name = "13", FullName = "Phường 13", NameEN = "13", FullNameEN = "Ward 13", DistrictId = "776", ProvinceId = "79" },
                    new AddressWard { Id = "27415", Name = "12", FullName = "Phường 12", NameEN = "12", FullNameEN = "Ward 12", DistrictId = "776", ProvinceId = "79" },
                    new AddressWard { Id = "27418", Name = "05", FullName = "Phường 05", NameEN = "05", FullNameEN = "Ward 05", DistrictId = "776", ProvinceId = "79" },
                    new AddressWard { Id = "27421", Name = "14", FullName = "Phường 14", NameEN = "14", FullNameEN = "Ward 14", DistrictId = "776", ProvinceId = "79" },
                    new AddressWard { Id = "27424", Name = "06", FullName = "Phường 06", NameEN = "06", FullNameEN = "Ward 06", DistrictId = "776", ProvinceId = "79" },
                    new AddressWard { Id = "27427", Name = "15", FullName = "Phường 15", NameEN = "15", FullNameEN = "Ward 15", DistrictId = "776", ProvinceId = "79" },
                    new AddressWard { Id = "27430", Name = "16", FullName = "Phường 16", NameEN = "16", FullNameEN = "Ward 16", DistrictId = "776", ProvinceId = "79" },
                    new AddressWard { Id = "27433", Name = "07", FullName = "Phường 07", NameEN = "07", FullNameEN = "Ward 07", DistrictId = "776", ProvinceId = "79" },
                    new AddressWard { Id = "27436", Name = "Bình Hưng Hòa", FullName = "Phường Bình Hưng Hòa", NameEN = "Binh Hung Hoa", FullNameEN = "Binh Hung Hoa Ward", DistrictId = "777", ProvinceId = "79" },
                    new AddressWard { Id = "27439", Name = "Bình Hưng Hoà A", FullName = "Phường Bình Hưng Hoà A", NameEN = "Binh Hung Hoa A", FullNameEN = "Binh Hung Hoa A Ward", DistrictId = "777", ProvinceId = "79" },
                    new AddressWard { Id = "27442", Name = "Bình Hưng Hoà B", FullName = "Phường Bình Hưng Hoà B", NameEN = "Binh Hung Hoa B", FullNameEN = "Binh Hung Hoa B Ward", DistrictId = "777", ProvinceId = "79" },
                    new AddressWard { Id = "27445", Name = "Bình Trị Đông", FullName = "Phường Bình Trị Đông", NameEN = "Binh Tri Dong", FullNameEN = "Binh Tri Dong Ward", DistrictId = "777", ProvinceId = "79" },
                    new AddressWard { Id = "27448", Name = "Bình Trị Đông A", FullName = "Phường Bình Trị Đông A", NameEN = "Binh Tri Dong A", FullNameEN = "Binh Tri Dong A Ward", DistrictId = "777", ProvinceId = "79" },
                    new AddressWard { Id = "27451", Name = "Bình Trị Đông B", FullName = "Phường Bình Trị Đông B", NameEN = "Binh Tri Dong B", FullNameEN = "Binh Tri Dong B Ward", DistrictId = "777", ProvinceId = "79" },
                    new AddressWard { Id = "27454", Name = "Tân Tạo", FullName = "Phường Tân Tạo", NameEN = "Tan Tao", FullNameEN = "Tan Tao Ward", DistrictId = "777", ProvinceId = "79" },
                    new AddressWard { Id = "27457", Name = "Tân Tạo A", FullName = "Phường Tân Tạo A", NameEN = "Tan Tao A", FullNameEN = "Tan Tao A Ward", DistrictId = "777", ProvinceId = "79" },
                    new AddressWard { Id = "27460", Name = "An Lạc", FullName = "Phường An Lạc", NameEN = "An Lac", FullNameEN = "An Lac Ward", DistrictId = "777", ProvinceId = "79" },
                    new AddressWard { Id = "27463", Name = "An Lạc A", FullName = "Phường An Lạc A", NameEN = "An Lac A", FullNameEN = "An Lac A Ward", DistrictId = "777", ProvinceId = "79" },
                    new AddressWard { Id = "27466", Name = "Tân Thuận Đông", FullName = "Phường Tân Thuận Đông", NameEN = "Tan Thuan Dong", FullNameEN = "Tan Thuan Dong Ward", DistrictId = "778", ProvinceId = "79" },
                    new AddressWard { Id = "27469", Name = "Tân Thuận Tây", FullName = "Phường Tân Thuận Tây", NameEN = "Tan Thuan Tay", FullNameEN = "Tan Thuan Tay Ward", DistrictId = "778", ProvinceId = "79" },
                    new AddressWard { Id = "27472", Name = "Tân Kiểng", FullName = "Phường Tân Kiểng", NameEN = "Tan Kieng", FullNameEN = "Tan Kieng Ward", DistrictId = "778", ProvinceId = "79" },
                    new AddressWard { Id = "27475", Name = "Tân Hưng", FullName = "Phường Tân Hưng", NameEN = "Tan Hung", FullNameEN = "Tan Hung Ward", DistrictId = "778", ProvinceId = "79" },
                    new AddressWard { Id = "27478", Name = "Bình Thuận", FullName = "Phường Bình Thuận", NameEN = "Binh Thuan", FullNameEN = "Binh Thuan Ward", DistrictId = "778", ProvinceId = "79" },
                    new AddressWard { Id = "27481", Name = "Tân Quy", FullName = "Phường Tân Quy", NameEN = "Tan Quy", FullNameEN = "Tan Quy Ward", DistrictId = "778", ProvinceId = "79" },
                    new AddressWard { Id = "27484", Name = "Phú Thuận", FullName = "Phường Phú Thuận", NameEN = "Phu Thuan", FullNameEN = "Phu Thuan Ward", DistrictId = "778", ProvinceId = "79" },
                    new AddressWard { Id = "27487", Name = "Tân Phú", FullName = "Phường Tân Phú", NameEN = "Tan Phu", FullNameEN = "Tan Phu Ward", DistrictId = "778", ProvinceId = "79" },
                    new AddressWard { Id = "27490", Name = "Tân Phong", FullName = "Phường Tân Phong", NameEN = "Tan Phong", FullNameEN = "Tan Phong Ward", DistrictId = "778", ProvinceId = "79" },
                    new AddressWard { Id = "27493", Name = "Phú Mỹ", FullName = "Phường Phú Mỹ", NameEN = "Phu My", FullNameEN = "Phu My Ward", DistrictId = "778", ProvinceId = "79" },
                    new AddressWard { Id = "27496", Name = "Củ Chi", FullName = "Thị trấn Củ Chi", NameEN = "Cu Chi", FullNameEN = "Cu Chi Township", DistrictId = "783", ProvinceId = "79" },
                    new AddressWard { Id = "27499", Name = "Phú Mỹ Hưng", FullName = "Xã Phú Mỹ Hưng", NameEN = "Phu My Hung", FullNameEN = "Phu My Hung Commune", DistrictId = "783", ProvinceId = "79" },
                    new AddressWard { Id = "27502", Name = "An Phú", FullName = "Xã An Phú", NameEN = "An Phu", FullNameEN = "An Phu Commune", DistrictId = "783", ProvinceId = "79" },
                    new AddressWard { Id = "27505", Name = "Trung Lập Thượng", FullName = "Xã Trung Lập Thượng", NameEN = "Trung Lap Thuong", FullNameEN = "Trung Lap Thuong Commune", DistrictId = "783", ProvinceId = "79" },
                    new AddressWard { Id = "27508", Name = "An Nhơn Tây", FullName = "Xã An Nhơn Tây", NameEN = "An Nhon Tay", FullNameEN = "An Nhon Tay Commune", DistrictId = "783", ProvinceId = "79" },
                    new AddressWard { Id = "27511", Name = "Nhuận Đức", FullName = "Xã Nhuận Đức", NameEN = "Nhuan Duc", FullNameEN = "Nhuan Duc Commune", DistrictId = "783", ProvinceId = "79" },
                    new AddressWard { Id = "27514", Name = "Phạm Văn Cội", FullName = "Xã Phạm Văn Cội", NameEN = "Pham Van Coi", FullNameEN = "Pham Van Coi Commune", DistrictId = "783", ProvinceId = "79" },
                    new AddressWard { Id = "27517", Name = "Phú Hòa Đông", FullName = "Xã Phú Hòa Đông", NameEN = "Phu Hoa Dong", FullNameEN = "Phu Hoa Dong Commune", DistrictId = "783", ProvinceId = "79" },
                    new AddressWard { Id = "27520", Name = "Trung Lập Hạ", FullName = "Xã Trung Lập Hạ", NameEN = "Trung Lap Ha", FullNameEN = "Trung Lap Ha Commune", DistrictId = "783", ProvinceId = "79" },
                    new AddressWard { Id = "27523", Name = "Trung An", FullName = "Xã Trung An", NameEN = "Trung An", FullNameEN = "Trung An Commune", DistrictId = "783", ProvinceId = "79" },
                    new AddressWard { Id = "27526", Name = "Phước Thạnh", FullName = "Xã Phước Thạnh", NameEN = "Phuoc Thanh", FullNameEN = "Phuoc Thanh Commune", DistrictId = "783", ProvinceId = "79" },
                    new AddressWard { Id = "27529", Name = "Phước Hiệp", FullName = "Xã Phước Hiệp", NameEN = "Phuoc Hiep", FullNameEN = "Phuoc Hiep Commune", DistrictId = "783", ProvinceId = "79" },
                    new AddressWard { Id = "27532", Name = "Tân An Hội", FullName = "Xã Tân An Hội", NameEN = "Tan An Hoi", FullNameEN = "Tan An Hoi Commune", DistrictId = "783", ProvinceId = "79" },
                    new AddressWard { Id = "27535", Name = "Phước Vĩnh An", FullName = "Xã Phước Vĩnh An", NameEN = "Phuoc Vinh An", FullNameEN = "Phuoc Vinh An Commune", DistrictId = "783", ProvinceId = "79" },
                    new AddressWard { Id = "27538", Name = "Thái Mỹ", FullName = "Xã Thái Mỹ", NameEN = "Thai My", FullNameEN = "Thai My Commune", DistrictId = "783", ProvinceId = "79" },
                    new AddressWard { Id = "27541", Name = "Tân Thạnh Tây", FullName = "Xã Tân Thạnh Tây", NameEN = "Tan Thanh Tay", FullNameEN = "Tan Thanh Tay Commune", DistrictId = "783", ProvinceId = "79" },
                    new AddressWard { Id = "27544", Name = "Hòa Phú", FullName = "Xã Hòa Phú", NameEN = "Hoa Phu", FullNameEN = "Hoa Phu Commune", DistrictId = "783", ProvinceId = "79" },
                    new AddressWard { Id = "27547", Name = "Tân Thạnh Đông", FullName = "Xã Tân Thạnh Đông", NameEN = "Tan Thanh Dong", FullNameEN = "Tan Thanh Dong Commune", DistrictId = "783", ProvinceId = "79" },
                    new AddressWard { Id = "27550", Name = "Bình Mỹ", FullName = "Xã Bình Mỹ", NameEN = "Binh My", FullNameEN = "Binh My Commune", DistrictId = "783", ProvinceId = "79" },
                    new AddressWard { Id = "27553", Name = "Tân Phú Trung", FullName = "Xã Tân Phú Trung", NameEN = "Tan Phu Trung", FullNameEN = "Tan Phu Trung Commune", DistrictId = "783", ProvinceId = "79" },
                    new AddressWard { Id = "27556", Name = "Tân Thông Hội", FullName = "Xã Tân Thông Hội", NameEN = "Tan Thong Hoi", FullNameEN = "Tan Thong Hoi Commune", DistrictId = "783", ProvinceId = "79" },
                    new AddressWard { Id = "27559", Name = "Hóc Môn", FullName = "Thị trấn Hóc Môn", NameEN = "Hoc Mon", FullNameEN = "Hoc Mon Township", DistrictId = "784", ProvinceId = "79" },
                    new AddressWard { Id = "27562", Name = "Tân Hiệp", FullName = "Xã Tân Hiệp", NameEN = "Tan Hiep", FullNameEN = "Tan Hiep Commune", DistrictId = "784", ProvinceId = "79" },
                    new AddressWard { Id = "27565", Name = "Nhị Bình", FullName = "Xã Nhị Bình", NameEN = "Nhi Binh", FullNameEN = "Nhi Binh Commune", DistrictId = "784", ProvinceId = "79" },
                    new AddressWard { Id = "27568", Name = "Đông Thạnh", FullName = "Xã Đông Thạnh", NameEN = "Dong Thanh", FullNameEN = "Dong Thanh Commune", DistrictId = "784", ProvinceId = "79" },
                    new AddressWard { Id = "27571", Name = "Tân Thới Nhì", FullName = "Xã Tân Thới Nhì", NameEN = "Tan Thoi Nhi", FullNameEN = "Tan Thoi Nhi Commune", DistrictId = "784", ProvinceId = "79" },
                    new AddressWard { Id = "27574", Name = "Thới Tam Thôn", FullName = "Xã Thới Tam Thôn", NameEN = "Thoi Tam Thon", FullNameEN = "Thoi Tam Thon Commune", DistrictId = "784", ProvinceId = "79" },
                    new AddressWard { Id = "27577", Name = "Xuân Thới Sơn", FullName = "Xã Xuân Thới Sơn", NameEN = "Xuan Thoi Son", FullNameEN = "Xuan Thoi Son Commune", DistrictId = "784", ProvinceId = "79" },
                    new AddressWard { Id = "27580", Name = "Tân Xuân", FullName = "Xã Tân Xuân", NameEN = "Tan Xuan", FullNameEN = "Tan Xuan Commune", DistrictId = "784", ProvinceId = "79" },
                    new AddressWard { Id = "27583", Name = "Xuân Thới Đông", FullName = "Xã Xuân Thới Đông", NameEN = "Xuan Thoi Dong", FullNameEN = "Xuan Thoi Dong Commune", DistrictId = "784", ProvinceId = "79" },
                    new AddressWard { Id = "27586", Name = "Trung Chánh", FullName = "Xã Trung Chánh", NameEN = "Trung Chanh", FullNameEN = "Trung Chanh Commune", DistrictId = "784", ProvinceId = "79" },
                    new AddressWard { Id = "27589", Name = "Xuân Thới Thượng", FullName = "Xã Xuân Thới Thượng", NameEN = "Xuan Thoi Thuong", FullNameEN = "Xuan Thoi Thuong Commune", DistrictId = "784", ProvinceId = "79" },
                    new AddressWard { Id = "27592", Name = "Bà Điểm", FullName = "Xã Bà Điểm", NameEN = "Ba Diem", FullNameEN = "Ba Diem Commune", DistrictId = "784", ProvinceId = "79" },
                    new AddressWard { Id = "27595", Name = "Tân Túc", FullName = "Thị trấn Tân Túc", NameEN = "Tan Tuc", FullNameEN = "Tan Tuc Township", DistrictId = "785", ProvinceId = "79" },
                    new AddressWard { Id = "27598", Name = "Phạm Văn Hai", FullName = "Xã Phạm Văn Hai", NameEN = "Pham Van Hai", FullNameEN = "Pham Van Hai Commune", DistrictId = "785", ProvinceId = "79" },
                    new AddressWard { Id = "27601", Name = "Vĩnh Lộc A", FullName = "Xã Vĩnh Lộc A", NameEN = "Vinh Loc A", FullNameEN = "Vinh Loc A Commune", DistrictId = "785", ProvinceId = "79" },
                    new AddressWard { Id = "27604", Name = "Vĩnh Lộc B", FullName = "Xã Vĩnh Lộc B", NameEN = "Vinh Loc B", FullNameEN = "Vinh Loc B Commune", DistrictId = "785", ProvinceId = "79" },
                    new AddressWard { Id = "27607", Name = "Bình Lợi", FullName = "Xã Bình Lợi", NameEN = "Binh Loi", FullNameEN = "Binh Loi Commune", DistrictId = "785", ProvinceId = "79" },
                    new AddressWard { Id = "27610", Name = "Lê Minh Xuân", FullName = "Xã Lê Minh Xuân", NameEN = "Le Minh Xuan", FullNameEN = "Le Minh Xuan Commune", DistrictId = "785", ProvinceId = "79" },
                    new AddressWard { Id = "27613", Name = "Tân Nhựt", FullName = "Xã Tân Nhựt", NameEN = "Tan Nhut", FullNameEN = "Tan Nhut Commune", DistrictId = "785", ProvinceId = "79" },
                    new AddressWard { Id = "27616", Name = "Tân Kiên", FullName = "Xã Tân Kiên", NameEN = "Tan Kien", FullNameEN = "Tan Kien Commune", DistrictId = "785", ProvinceId = "79" },
                    new AddressWard { Id = "27619", Name = "Bình Hưng", FullName = "Xã Bình Hưng", NameEN = "Binh Hung", FullNameEN = "Binh Hung Commune", DistrictId = "785", ProvinceId = "79" },
                    new AddressWard { Id = "27622", Name = "Phong Phú", FullName = "Xã Phong Phú", NameEN = "Phong Phu", FullNameEN = "Phong Phu Commune", DistrictId = "785", ProvinceId = "79" },
                    new AddressWard { Id = "27625", Name = "An Phú Tây", FullName = "Xã An Phú Tây", NameEN = "An Phu Tay", FullNameEN = "An Phu Tay Commune", DistrictId = "785", ProvinceId = "79" },
                    new AddressWard { Id = "27628", Name = "Hưng Long", FullName = "Xã Hưng Long", NameEN = "Hung Long", FullNameEN = "Hung Long Commune", DistrictId = "785", ProvinceId = "79" },
                    new AddressWard { Id = "27631", Name = "Đa Phước", FullName = "Xã Đa Phước", NameEN = "Da Phuoc", FullNameEN = "Da Phuoc Commune", DistrictId = "785", ProvinceId = "79" },
                    new AddressWard { Id = "27634", Name = "Tân Quý Tây", FullName = "Xã Tân Quý Tây", NameEN = "Tan Quy Tay", FullNameEN = "Tan Quy Tay Commune", DistrictId = "785", ProvinceId = "79" },
                    new AddressWard { Id = "27637", Name = "Bình Chánh", FullName = "Xã Bình Chánh", NameEN = "Binh Chanh", FullNameEN = "Binh Chanh Commune", DistrictId = "785", ProvinceId = "79" },
                    new AddressWard { Id = "27640", Name = "Quy Đức", FullName = "Xã Quy Đức", NameEN = "Quy Duc", FullNameEN = "Quy Duc Commune", DistrictId = "785", ProvinceId = "79" },
                    new AddressWard { Id = "27643", Name = "Nhà Bè", FullName = "Thị trấn Nhà Bè", NameEN = "Nha Be", FullNameEN = "Nha Be Township", DistrictId = "786", ProvinceId = "79" },
                    new AddressWard { Id = "27646", Name = "Phước Kiển", FullName = "Xã Phước Kiển", NameEN = "Phuoc Kien", FullNameEN = "Phuoc Kien Commune", DistrictId = "786", ProvinceId = "79" },
                    new AddressWard { Id = "27649", Name = "Phước Lộc", FullName = "Xã Phước Lộc", NameEN = "Phuoc Loc", FullNameEN = "Phuoc Loc Commune", DistrictId = "786", ProvinceId = "79" },
                    new AddressWard { Id = "27652", Name = "Nhơn Đức", FullName = "Xã Nhơn Đức", NameEN = "Nhon Duc", FullNameEN = "Nhon Duc Commune", DistrictId = "786", ProvinceId = "79" },
                    new AddressWard { Id = "27655", Name = "Phú Xuân", FullName = "Xã Phú Xuân", NameEN = "Phu Xuan", FullNameEN = "Phu Xuan Commune", DistrictId = "786", ProvinceId = "79" },
                    new AddressWard { Id = "27658", Name = "Long Thới", FullName = "Xã Long Thới", NameEN = "Long Thoi", FullNameEN = "Long Thoi Commune", DistrictId = "786", ProvinceId = "79" },
                    new AddressWard { Id = "27661", Name = "Hiệp Phước", FullName = "Xã Hiệp Phước", NameEN = "Hiep Phuoc", FullNameEN = "Hiep Phuoc Commune", DistrictId = "786", ProvinceId = "79" },
                    new AddressWard { Id = "27664", Name = "Cần Thạnh", FullName = "Thị trấn Cần Thạnh", NameEN = "Can Thanh", FullNameEN = "Can Thanh Township", DistrictId = "787", ProvinceId = "79" },
                    new AddressWard { Id = "27667", Name = "Bình Khánh", FullName = "Xã Bình Khánh", NameEN = "Binh Khanh", FullNameEN = "Binh Khanh Commune", DistrictId = "787", ProvinceId = "79" },
                    new AddressWard { Id = "27670", Name = "Tam Thôn Hiệp", FullName = "Xã Tam Thôn Hiệp", NameEN = "Tam Thon Hiep", FullNameEN = "Tam Thon Hiep Commune", DistrictId = "787", ProvinceId = "79" },
                    new AddressWard { Id = "27673", Name = "An Thới Đông", FullName = "Xã An Thới Đông", NameEN = "An Thoi Dong", FullNameEN = "An Thoi Dong Commune", DistrictId = "787", ProvinceId = "79" },
                    new AddressWard { Id = "27676", Name = "Thạnh An", FullName = "Xã Thạnh An", NameEN = "Thanh An", FullNameEN = "Thanh An Commune", DistrictId = "787", ProvinceId = "79" },
                    new AddressWard { Id = "27679", Name = "Long Hòa", FullName = "Xã Long Hòa", NameEN = "Long Hoa", FullNameEN = "Long Hoa Commune", DistrictId = "787", ProvinceId = "79" },
                    new AddressWard { Id = "27682", Name = "Lý Nhơn", FullName = "Xã Lý Nhơn", NameEN = "Ly Nhon", FullNameEN = "Ly Nhon Commune", DistrictId = "787", ProvinceId = "79" }
                    );
            }
        }
    
}
