INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'001',N'Ba Đình',N'Quận Ba Đình',N'Ba Dinh',N'Ba Dinh District',N'01'),
	 (N'002',N'Hoàn Kiếm',N'Quận Hoàn Kiếm',N'Hoan Kiem',N'Hoan Kiem District',N'01'),
	 (N'003',N'Tây Hồ',N'Quận Tây Hồ',N'Tay Ho',N'Tay Ho District',N'01'),
	 (N'004',N'Long Biên',N'Quận Long Biên',N'Long Bien',N'Long Bien District',N'01'),
	 (N'005',N'Cầu Giấy',N'Quận Cầu Giấy',N'Cau Giay',N'Cau Giay District',N'01'),
	 (N'006',N'Đống Đa',N'Quận Đống Đa',N'Dong Da',N'Dong Da District',N'01'),
	 (N'007',N'Hai Bà Trưng',N'Quận Hai Bà Trưng',N'Hai Ba Trung',N'Hai Ba Trung District',N'01'),
	 (N'008',N'Hoàng Mai',N'Quận Hoàng Mai',N'Hoang Mai',N'Hoang Mai District',N'01'),
	 (N'009',N'Thanh Xuân',N'Quận Thanh Xuân',N'Thanh Xuan',N'Thanh Xuan District',N'01'),
	 (N'016',N'Sóc Sơn',N'Huyện Sóc Sơn',N'Soc Son',N'Soc Son District',N'01');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'017',N'Đông Anh',N'Huyện Đông Anh',N'Dong Anh',N'Dong Anh District',N'01'),
	 (N'018',N'Gia Lâm',N'Huyện Gia Lâm',N'Gia Lam',N'Gia Lam District',N'01'),
	 (N'019',N'Nam Từ Liêm',N'Quận Nam Từ Liêm',N'Nam Tu Liem',N'Nam Tu Liem District',N'01'),
	 (N'020',N'Thanh Trì',N'Huyện Thanh Trì',N'Thanh Tri',N'Thanh Tri District',N'01'),
	 (N'021',N'Bắc Từ Liêm',N'Quận Bắc Từ Liêm',N'Bac Tu Liem',N'Bac Tu Liem District',N'01'),
	 (N'024',N'Hà Giang',N'Thành phố Hà Giang',N'Ha Giang',N'Ha Giang City',N'02'),
	 (N'026',N'Đồng Văn',N'Huyện Đồng Văn',N'Dong Van',N'Dong Van District',N'02'),
	 (N'027',N'Mèo Vạc',N'Huyện Mèo Vạc',N'Meo Vac',N'Meo Vac District',N'02'),
	 (N'028',N'Yên Minh',N'Huyện Yên Minh',N'Yen Minh',N'Yen Minh District',N'02'),
	 (N'029',N'Quản Bạ',N'Huyện Quản Bạ',N'Quan Ba',N'Quan Ba District',N'02');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'030',N'Vị Xuyên',N'Huyện Vị Xuyên',N'Vi Xuyen',N'Vi Xuyen District',N'02'),
	 (N'031',N'Bắc Mê',N'Huyện Bắc Mê',N'Bac Me',N'Bac Me District',N'02'),
	 (N'032',N'Hoàng Su Phì',N'Huyện Hoàng Su Phì',N'Hoang Su Phi',N'Hoang Su Phi District',N'02'),
	 (N'033',N'Xín Mần',N'Huyện Xín Mần',N'Xin Man',N'Xin Man District',N'02'),
	 (N'034',N'Bắc Quang',N'Huyện Bắc Quang',N'Bac Quang',N'Bac Quang District',N'02'),
	 (N'035',N'Quang Bình',N'Huyện Quang Bình',N'Quang Binh',N'Quang Binh District',N'02'),
	 (N'040',N'Cao Bằng',N'Thành phố Cao Bằng',N'Cao Bang',N'Cao Bang City',N'04'),
	 (N'042',N'Bảo Lâm',N'Huyện Bảo Lâm',N'Bao Lam',N'Bao Lam District',N'04'),
	 (N'043',N'Bảo Lạc',N'Huyện Bảo Lạc',N'Bao Lac',N'Bao Lac District',N'04'),
	 (N'045',N'Hà Quảng',N'Huyện Hà Quảng',N'Ha Quang',N'Ha Quang District',N'04');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'047',N'Trùng Khánh',N'Huyện Trùng Khánh',N'Trung Khanh',N'Trung Khanh District',N'04'),
	 (N'048',N'Hạ Lang',N'Huyện Hạ Lang',N'Ha Lang',N'Ha Lang District',N'04'),
	 (N'049',N'Quảng Hòa',N'Huyện Quảng Hòa',N'Quang Hoa',N'Quang Hoa District',N'04'),
	 (N'051',N'Hoà An',N'Huyện Hoà An',N'Hoa An',N'Hoa An District',N'04'),
	 (N'052',N'Nguyên Bình',N'Huyện Nguyên Bình',N'Nguyen Binh',N'Nguyen Binh District',N'04'),
	 (N'053',N'Thạch An',N'Huyện Thạch An',N'Thach An',N'Thach An District',N'04'),
	 (N'058',N'Bắc Kạn',N'Thành phố Bắc Kạn',N'Bac Kan',N'Bac Kan City',N'06'),
	 (N'060',N'Pác Nặm',N'Huyện Pác Nặm',N'Pac Nam',N'Pac Nam District',N'06'),
	 (N'061',N'Ba Bể',N'Huyện Ba Bể',N'Ba Be',N'Ba Be District',N'06'),
	 (N'062',N'Ngân Sơn',N'Huyện Ngân Sơn',N'Ngan Son',N'Ngan Son District',N'06');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'063',N'Bạch Thông',N'Huyện Bạch Thông',N'Bach Thong',N'Bach Thong District',N'06'),
	 (N'064',N'Chợ Đồn',N'Huyện Chợ Đồn',N'Cho Don',N'Cho Don District',N'06'),
	 (N'065',N'Chợ Mới',N'Huyện Chợ Mới',N'Cho Moi',N'Cho Moi District',N'06'),
	 (N'066',N'Na Rì',N'Huyện Na Rì',N'Na Ri',N'Na Ri District',N'06'),
	 (N'070',N'Tuyên Quang',N'Thành phố Tuyên Quang',N'Tuyen Quang',N'Tuyen Quang City',N'08'),
	 (N'071',N'Lâm Bình',N'Huyện Lâm Bình',N'Lam Binh',N'Lam Binh District',N'08'),
	 (N'072',N'Na Hang',N'Huyện Na Hang',N'Na Hang',N'Na Hang District',N'08'),
	 (N'073',N'Chiêm Hóa',N'Huyện Chiêm Hóa',N'Chiem Hoa',N'Chiem Hoa District',N'08'),
	 (N'074',N'Hàm Yên',N'Huyện Hàm Yên',N'Ham Yen',N'Ham Yen District',N'08'),
	 (N'075',N'Yên Sơn',N'Huyện Yên Sơn',N'Yen Son',N'Yen Son District',N'08');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'076',N'Sơn Dương',N'Huyện Sơn Dương',N'Son Duong',N'Son Duong District',N'08'),
	 (N'080',N'Lào Cai',N'Thành phố Lào Cai',N'Lao Cai',N'Lao Cai City',N'10'),
	 (N'082',N'Bát Xát',N'Huyện Bát Xát',N'Bat Xat',N'Bat Xat District',N'10'),
	 (N'083',N'Mường Khương',N'Huyện Mường Khương',N'Muong Khuong',N'Muong Khuong District',N'10'),
	 (N'084',N'Si Ma Cai',N'Huyện Si Ma Cai',N'Si Ma Cai',N'Si Ma Cai District',N'10'),
	 (N'085',N'Bắc Hà',N'Huyện Bắc Hà',N'Bac Ha',N'Bac Ha District',N'10'),
	 (N'086',N'Bảo Thắng',N'Huyện Bảo Thắng',N'Bao Thang',N'Bao Thang District',N'10'),
	 (N'087',N'Bảo Yên',N'Huyện Bảo Yên',N'Bao Yen',N'Bao Yen District',N'10'),
	 (N'088',N'Sa Pa',N'Thị xã Sa Pa',N'Sa Pa',N'Sa Pa Town',N'10'),
	 (N'089',N'Văn Bàn',N'Huyện Văn Bàn',N'Van Ban',N'Van Ban District',N'10');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'094',N'Điện Biên Phủ',N'Thành phố Điện Biên Phủ',N'Dien Bien Phu',N'Dien Bien Phu City',N'11'),
	 (N'095',N'Mường Lay',N'Thị xã Mường Lay',N'Muong Lay',N'Muong Lay Town',N'11'),
	 (N'096',N'Mường Nhé',N'Huyện Mường Nhé',N'Muong Nhe',N'Muong Nhe District',N'11'),
	 (N'097',N'Mường Chà',N'Huyện Mường Chà',N'Muong Cha',N'Muong Cha District',N'11'),
	 (N'098',N'Tủa Chùa',N'Huyện Tủa Chùa',N'Tua Chua',N'Tua Chua District',N'11'),
	 (N'099',N'Tuần Giáo',N'Huyện Tuần Giáo',N'Tuan Giao',N'Tuan Giao District',N'11'),
	 (N'100',N'Điện Biên',N'Huyện Điện Biên',N'Dien Bien',N'Dien Bien District',N'11'),
	 (N'101',N'Điện Biên Đông',N'Huyện Điện Biên Đông',N'Dien Bien Dong',N'Dien Bien Dong District',N'11'),
	 (N'102',N'Mường Ảng',N'Huyện Mường Ảng',N'Muong Ang',N'Muong Ang District',N'11'),
	 (N'103',N'Nậm Pồ',N'Huyện Nậm Pồ',N'Nam Po',N'Nam Po District',N'11');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'105',N'Lai Châu',N'Thành phố Lai Châu',N'Lai Chau',N'Lai Chau City',N'12'),
	 (N'106',N'Tam Đường',N'Huyện Tam Đường',N'Tam Duong',N'Tam Duong District',N'12'),
	 (N'107',N'Mường Tè',N'Huyện Mường Tè',N'Muong Te',N'Muong Te District',N'12'),
	 (N'108',N'Sìn Hồ',N'Huyện Sìn Hồ',N'Sin Ho',N'Sin Ho District',N'12'),
	 (N'109',N'Phong Thổ',N'Huyện Phong Thổ',N'Phong Tho',N'Phong Tho District',N'12'),
	 (N'110',N'Than Uyên',N'Huyện Than Uyên',N'Than Uyen',N'Than Uyen District',N'12'),
	 (N'111',N'Tân Uyên',N'Huyện Tân Uyên',N'Tan Uyen',N'Tan Uyen District',N'12'),
	 (N'112',N'Nậm Nhùn',N'Huyện Nậm Nhùn',N'Nam Nhun',N'Nam Nhun District',N'12'),
	 (N'116',N'Sơn La',N'Thành phố Sơn La',N'Son La',N'Son La City',N'14'),
	 (N'118',N'Quỳnh Nhai',N'Huyện Quỳnh Nhai',N'Quynh Nhai',N'Quynh Nhai District',N'14');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'119',N'Thuận Châu',N'Huyện Thuận Châu',N'Thuan Chau',N'Thuan Chau District',N'14'),
	 (N'120',N'Mường La',N'Huyện Mường La',N'Muong La',N'Muong La District',N'14'),
	 (N'121',N'Bắc Yên',N'Huyện Bắc Yên',N'Bac Yen',N'Bac Yen District',N'14'),
	 (N'122',N'Phù Yên',N'Huyện Phù Yên',N'Phu Yen',N'Phu Yen District',N'14'),
	 (N'123',N'Mộc Châu',N'Huyện Mộc Châu',N'Moc Chau',N'Moc Chau District',N'14'),
	 (N'124',N'Yên Châu',N'Huyện Yên Châu',N'Yen Chau',N'Yen Chau District',N'14'),
	 (N'125',N'Mai Sơn',N'Huyện Mai Sơn',N'Mai Son',N'Mai Son District',N'14'),
	 (N'126',N'Sông Mã',N'Huyện Sông Mã',N'Song Ma',N'Song Ma District',N'14'),
	 (N'127',N'Sốp Cộp',N'Huyện Sốp Cộp',N'Sop Cop',N'Sop Cop District',N'14'),
	 (N'128',N'Vân Hồ',N'Huyện Vân Hồ',N'Van Ho',N'Van Ho District',N'14');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'132',N'Yên Bái',N'Thành phố Yên Bái',N'Yen Bai',N'Yen Bai City',N'15'),
	 (N'133',N'Nghĩa Lộ',N'Thị xã Nghĩa Lộ',N'Nghia Lo',N'Nghia Lo Town',N'15'),
	 (N'135',N'Lục Yên',N'Huyện Lục Yên',N'Luc Yen',N'Luc Yen District',N'15'),
	 (N'136',N'Văn Yên',N'Huyện Văn Yên',N'Van Yen',N'Van Yen District',N'15'),
	 (N'137',N'Mù Căng Chải',N'Huyện Mù Căng Chải',N'Mu Cang Chai',N'Mu Cang Chai District',N'15'),
	 (N'138',N'Trấn Yên',N'Huyện Trấn Yên',N'Tran Yen',N'Tran Yen District',N'15'),
	 (N'139',N'Trạm Tấu',N'Huyện Trạm Tấu',N'Tram Tau',N'Tram Tau District',N'15'),
	 (N'140',N'Văn Chấn',N'Huyện Văn Chấn',N'Van Chan',N'Van Chan District',N'15'),
	 (N'141',N'Yên Bình',N'Huyện Yên Bình',N'Yen Binh',N'Yen Binh District',N'15'),
	 (N'148',N'Hòa Bình',N'Thành phố Hòa Bình',N'Hoa Binh',N'Hoa Binh City',N'17');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'150',N'Đà Bắc',N'Huyện Đà Bắc',N'Da Bac',N'Da Bac District',N'17'),
	 (N'152',N'Lương Sơn',N'Huyện Lương Sơn',N'Luong Son',N'Luong Son District',N'17'),
	 (N'153',N'Kim Bôi',N'Huyện Kim Bôi',N'Kim Boi',N'Kim Boi District',N'17'),
	 (N'154',N'Cao Phong',N'Huyện Cao Phong',N'Cao Phong',N'Cao Phong District',N'17'),
	 (N'155',N'Tân Lạc',N'Huyện Tân Lạc',N'Tan Lac',N'Tan Lac District',N'17'),
	 (N'156',N'Mai Châu',N'Huyện Mai Châu',N'Mai Chau',N'Mai Chau District',N'17'),
	 (N'157',N'Lạc Sơn',N'Huyện Lạc Sơn',N'Lac Son',N'Lac Son District',N'17'),
	 (N'158',N'Yên Thủy',N'Huyện Yên Thủy',N'Yen Thuy',N'Yen Thuy District',N'17'),
	 (N'159',N'Lạc Thủy',N'Huyện Lạc Thủy',N'Lac Thuy',N'Lac Thuy District',N'17'),
	 (N'164',N'Thái Nguyên',N'Thành phố Thái Nguyên',N'Thai Nguyen',N'Thai Nguyen City',N'19');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'165',N'Sông Công',N'Thành phố Sông Công',N'Song Cong',N'Song Cong City',N'19'),
	 (N'167',N'Định Hóa',N'Huyện Định Hóa',N'Dinh Hoa',N'Dinh Hoa District',N'19'),
	 (N'168',N'Phú Lương',N'Huyện Phú Lương',N'Phu Luong',N'Phu Luong District',N'19'),
	 (N'169',N'Đồng Hỷ',N'Huyện Đồng Hỷ',N'Dong Hy',N'Dong Hy District',N'19'),
	 (N'170',N'Võ Nhai',N'Huyện Võ Nhai',N'Vo Nhai',N'Vo Nhai District',N'19'),
	 (N'171',N'Đại Từ',N'Huyện Đại Từ',N'Dai Tu',N'Dai Tu District',N'19'),
	 (N'172',N'Phổ Yên',N'Thành phố Phổ Yên',N'Pho Yen',N'Pho Yen City',N'19'),
	 (N'173',N'Phú Bình',N'Huyện Phú Bình',N'Phu Binh',N'Phu Binh District',N'19'),
	 (N'178',N'Lạng Sơn',N'Thành phố Lạng Sơn',N'Lang Son',N'Lang Son City',N'20'),
	 (N'180',N'Tràng Định',N'Huyện Tràng Định',N'Trang Dinh',N'Trang Dinh District',N'20');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'181',N'Bình Gia',N'Huyện Bình Gia',N'Binh Gia',N'Binh Gia District',N'20'),
	 (N'182',N'Văn Lãng',N'Huyện Văn Lãng',N'Van Lang',N'Van Lang District',N'20'),
	 (N'183',N'Cao Lộc',N'Huyện Cao Lộc',N'Cao Loc',N'Cao Loc District',N'20'),
	 (N'184',N'Văn Quan',N'Huyện Văn Quan',N'Van Quan',N'Van Quan District',N'20'),
	 (N'185',N'Bắc Sơn',N'Huyện Bắc Sơn',N'Bac Son',N'Bac Son District',N'20'),
	 (N'186',N'Hữu Lũng',N'Huyện Hữu Lũng',N'Huu Lung',N'Huu Lung District',N'20'),
	 (N'187',N'Chi Lăng',N'Huyện Chi Lăng',N'Chi Lang',N'Chi Lang District',N'20'),
	 (N'188',N'Lộc Bình',N'Huyện Lộc Bình',N'Loc Binh',N'Loc Binh District',N'20'),
	 (N'189',N'Đình Lập',N'Huyện Đình Lập',N'Dinh Lap',N'Dinh Lap District',N'20'),
	 (N'193',N'Hạ Long',N'Thành phố Hạ Long',N'Ha Long',N'Ha Long City',N'22');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'194',N'Móng Cái',N'Thành phố Móng Cái',N'Mong Cai',N'Mong Cai City',N'22'),
	 (N'195',N'Cẩm Phả',N'Thành phố Cẩm Phả',N'Cam Pha',N'Cam Pha City',N'22'),
	 (N'196',N'Uông Bí',N'Thành phố Uông Bí',N'Uong Bi',N'Uong Bi City',N'22'),
	 (N'198',N'Bình Liêu',N'Huyện Bình Liêu',N'Binh Lieu',N'Binh Lieu District',N'22'),
	 (N'199',N'Tiên Yên',N'Huyện Tiên Yên',N'Tien Yen',N'Tien Yen District',N'22'),
	 (N'200',N'Đầm Hà',N'Huyện Đầm Hà',N'Dam Ha',N'Dam Ha District',N'22'),
	 (N'201',N'Hải Hà',N'Huyện Hải Hà',N'Hai Ha',N'Hai Ha District',N'22'),
	 (N'202',N'Ba Chẽ',N'Huyện Ba Chẽ',N'Ba Che',N'Ba Che District',N'22'),
	 (N'203',N'Vân Đồn',N'Huyện Vân Đồn',N'Van Don',N'Van Don District',N'22'),
	 (N'205',N'Đông Triều',N'Thị xã Đông Triều',N'Dong Trieu',N'Dong Trieu Town',N'22');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'206',N'Quảng Yên',N'Thị xã Quảng Yên',N'Quang Yen',N'Quang Yen Town',N'22'),
	 (N'207',N'Cô Tô',N'Huyện Cô Tô',N'Co To',N'Co To District',N'22'),
	 (N'213',N'Bắc Giang',N'Thành phố Bắc Giang',N'Bac Giang',N'Bac Giang City',N'24'),
	 (N'215',N'Yên Thế',N'Huyện Yên Thế',N'Yen The',N'Yen The District',N'24'),
	 (N'216',N'Tân Yên',N'Huyện Tân Yên',N'Tan Yen',N'Tan Yen District',N'24'),
	 (N'217',N'Lạng Giang',N'Huyện Lạng Giang',N'Lang Giang',N'Lang Giang District',N'24'),
	 (N'218',N'Lục Nam',N'Huyện Lục Nam',N'Luc Nam',N'Luc Nam District',N'24'),
	 (N'219',N'Lục Ngạn',N'Huyện Lục Ngạn',N'Luc Ngan',N'Luc Ngan District',N'24'),
	 (N'220',N'Sơn Động',N'Huyện Sơn Động',N'Son Dong',N'Son Dong District',N'24'),
	 (N'221',N'Yên Dũng',N'Huyện Yên Dũng',N'Yen Dung',N'Yen Dung District',N'24');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'222',N'Việt Yên',N'Huyện Việt Yên',N'Viet Yen',N'Viet Yen District',N'24'),
	 (N'223',N'Hiệp Hòa',N'Huyện Hiệp Hòa',N'Hiep Hoa',N'Hiep Hoa District',N'24'),
	 (N'227',N'Việt Trì',N'Thành phố Việt Trì',N'Viet Tri',N'Viet Tri City',N'25'),
	 (N'228',N'Phú Thọ',N'Thị xã Phú Thọ',N'Phu Tho',N'Phu Tho Town',N'25'),
	 (N'230',N'Đoan Hùng',N'Huyện Đoan Hùng',N'Doan Hung',N'Doan Hung District',N'25'),
	 (N'231',N'Hạ Hoà',N'Huyện Hạ Hoà',N'Ha Hoa',N'Ha Hoa District',N'25'),
	 (N'232',N'Thanh Ba',N'Huyện Thanh Ba',N'Thanh Ba',N'Thanh Ba District',N'25'),
	 (N'233',N'Phù Ninh',N'Huyện Phù Ninh',N'Phu Ninh',N'Phu Ninh District',N'25'),
	 (N'234',N'Yên Lập',N'Huyện Yên Lập',N'Yen Lap',N'Yen Lap District',N'25'),
	 (N'235',N'Cẩm Khê',N'Huyện Cẩm Khê',N'Cam Khe',N'Cam Khe District',N'25');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'236',N'Tam Nông',N'Huyện Tam Nông',N'Tam Nong',N'Tam Nong District',N'25'),
	 (N'237',N'Lâm Thao',N'Huyện Lâm Thao',N'Lam Thao',N'Lam Thao District',N'25'),
	 (N'238',N'Thanh Sơn',N'Huyện Thanh Sơn',N'Thanh Son',N'Thanh Son District',N'25'),
	 (N'239',N'Thanh Thuỷ',N'Huyện Thanh Thuỷ',N'Thanh Thuy',N'Thanh Thuy District',N'25'),
	 (N'240',N'Tân Sơn',N'Huyện Tân Sơn',N'Tan Son',N'Tan Son District',N'25'),
	 (N'243',N'Vĩnh Yên',N'Thành phố Vĩnh Yên',N'Vinh Yen',N'Vinh Yen City',N'26'),
	 (N'244',N'Phúc Yên',N'Thành phố Phúc Yên',N'Phuc Yen',N'Phuc Yen City',N'26'),
	 (N'246',N'Lập Thạch',N'Huyện Lập Thạch',N'Lap Thach',N'Lap Thach District',N'26'),
	 (N'247',N'Tam Dương',N'Huyện Tam Dương',N'Tam Duong',N'Tam Duong District',N'26'),
	 (N'248',N'Tam Đảo',N'Huyện Tam Đảo',N'Tam Dao',N'Tam Dao District',N'26');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'249',N'Bình Xuyên',N'Huyện Bình Xuyên',N'Binh Xuyen',N'Binh Xuyen District',N'26'),
	 (N'250',N'Mê Linh',N'Huyện Mê Linh',N'Me Linh',N'Me Linh District',N'01'),
	 (N'251',N'Yên Lạc',N'Huyện Yên Lạc',N'Yen Lac',N'Yen Lac District',N'26'),
	 (N'252',N'Vĩnh Tường',N'Huyện Vĩnh Tường',N'Vinh Tuong',N'Vinh Tuong District',N'26'),
	 (N'253',N'Sông Lô',N'Huyện Sông Lô',N'Song Lo',N'Song Lo District',N'26'),
	 (N'256',N'Bắc Ninh',N'Thành phố Bắc Ninh',N'Bac Ninh',N'Bac Ninh City',N'27'),
	 (N'258',N'Yên Phong',N'Huyện Yên Phong',N'Yen Phong',N'Yen Phong District',N'27'),
	 (N'259',N'Quế Võ',N'Thị xã Quế Võ',N'Que Vo',N'Que Vo Town',N'27'),
	 (N'260',N'Tiên Du',N'Huyện Tiên Du',N'Tien Du',N'Tien Du District',N'27'),
	 (N'261',N'Từ Sơn',N'Thành phố Từ Sơn',N'Tu Son',N'Tu Son City',N'27');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'262',N'Thuận Thành',N'Thị xã Thuận Thành',N'Thuan Thanh',N'Thuan Thanh Town',N'27'),
	 (N'263',N'Gia Bình',N'Huyện Gia Bình',N'Gia Binh',N'Gia Binh District',N'27'),
	 (N'264',N'Lương Tài',N'Huyện Lương Tài',N'Luong Tai',N'Luong Tai District',N'27'),
	 (N'268',N'Hà Đông',N'Quận Hà Đông',N'Ha Dong',N'Ha Dong District',N'01'),
	 (N'269',N'Sơn Tây',N'Thị xã Sơn Tây',N'Son Tay',N'Son Tay Town',N'01'),
	 (N'271',N'Ba Vì',N'Huyện Ba Vì',N'Ba Vi',N'Ba Vi District',N'01'),
	 (N'272',N'Phúc Thọ',N'Huyện Phúc Thọ',N'Phuc Tho',N'Phuc Tho District',N'01'),
	 (N'273',N'Đan Phượng',N'Huyện Đan Phượng',N'Dan Phuong',N'Dan Phuong District',N'01'),
	 (N'274',N'Hoài Đức',N'Huyện Hoài Đức',N'Hoai Duc',N'Hoai Duc District',N'01'),
	 (N'275',N'Quốc Oai',N'Huyện Quốc Oai',N'Quoc Oai',N'Quoc Oai District',N'01');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'276',N'Thạch Thất',N'Huyện Thạch Thất',N'Thach That',N'Thach That District',N'01'),
	 (N'277',N'Chương Mỹ',N'Huyện Chương Mỹ',N'Chuong My',N'Chuong My District',N'01'),
	 (N'278',N'Thanh Oai',N'Huyện Thanh Oai',N'Thanh Oai',N'Thanh Oai District',N'01'),
	 (N'279',N'Thường Tín',N'Huyện Thường Tín',N'Thuong Tin',N'Thuong Tin District',N'01'),
	 (N'280',N'Phú Xuyên',N'Huyện Phú Xuyên',N'Phu Xuyen',N'Phu Xuyen District',N'01'),
	 (N'281',N'Ứng Hòa',N'Huyện Ứng Hòa',N'Ung Hoa',N'Ung Hoa District',N'01'),
	 (N'282',N'Mỹ Đức',N'Huyện Mỹ Đức',N'My Duc',N'My Duc District',N'01'),
	 (N'288',N'Hải Dương',N'Thành phố Hải Dương',N'Hai Duong',N'Hai Duong City',N'30'),
	 (N'290',N'Chí Linh',N'Thành phố Chí Linh',N'Chi Linh',N'Chi Linh City',N'30'),
	 (N'291',N'Nam Sách',N'Huyện Nam Sách',N'Nam Sach',N'Nam Sach District',N'30');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'292',N'Kinh Môn',N'Thị xã Kinh Môn',N'Kinh Mon',N'Kinh Mon Town',N'30'),
	 (N'293',N'Kim Thành',N'Huyện Kim Thành',N'Kim Thanh',N'Kim Thanh District',N'30'),
	 (N'294',N'Thanh Hà',N'Huyện Thanh Hà',N'Thanh Ha',N'Thanh Ha District',N'30'),
	 (N'295',N'Cẩm Giàng',N'Huyện Cẩm Giàng',N'Cam Giang',N'Cam Giang District',N'30'),
	 (N'296',N'Bình Giang',N'Huyện Bình Giang',N'Binh Giang',N'Binh Giang District',N'30'),
	 (N'297',N'Gia Lộc',N'Huyện Gia Lộc',N'Gia Loc',N'Gia Loc District',N'30'),
	 (N'298',N'Tứ Kỳ',N'Huyện Tứ Kỳ',N'Tu Ky',N'Tu Ky District',N'30'),
	 (N'299',N'Ninh Giang',N'Huyện Ninh Giang',N'Ninh Giang',N'Ninh Giang District',N'30'),
	 (N'300',N'Thanh Miện',N'Huyện Thanh Miện',N'Thanh Mien',N'Thanh Mien District',N'30'),
	 (N'303',N'Hồng Bàng',N'Quận Hồng Bàng',N'Hong Bang',N'Hong Bang District',N'31');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'304',N'Ngô Quyền',N'Quận Ngô Quyền',N'Ngo Quyen',N'Ngo Quyen District',N'31'),
	 (N'305',N'Lê Chân',N'Quận Lê Chân',N'Le Chan',N'Le Chan District',N'31'),
	 (N'306',N'Hải An',N'Quận Hải An',N'Hai An',N'Hai An District',N'31'),
	 (N'307',N'Kiến An',N'Quận Kiến An',N'Kien An',N'Kien An District',N'31'),
	 (N'308',N'Đồ Sơn',N'Quận Đồ Sơn',N'Do Son',N'Do Son District',N'31'),
	 (N'309',N'Dương Kinh',N'Quận Dương Kinh',N'Duong Kinh',N'Duong Kinh District',N'31'),
	 (N'311',N'Thuỷ Nguyên',N'Huyện Thuỷ Nguyên',N'Thuy Nguyen',N'Thuy Nguyen District',N'31'),
	 (N'312',N'An Dương',N'Huyện An Dương',N'An Duong',N'An Duong District',N'31'),
	 (N'313',N'An Lão',N'Huyện An Lão',N'An Lao',N'An Lao District',N'31'),
	 (N'314',N'Kiến Thuỵ',N'Huyện Kiến Thuỵ',N'Kien Thuy',N'Kien Thuy District',N'31');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'315',N'Tiên Lãng',N'Huyện Tiên Lãng',N'Tien Lang',N'Tien Lang District',N'31'),
	 (N'316',N'Vĩnh Bảo',N'Huyện Vĩnh Bảo',N'Vinh Bao',N'Vinh Bao District',N'31'),
	 (N'317',N'Cát Hải',N'Huyện Cát Hải',N'Cat Hai',N'Cat Hai District',N'31'),
	 (N'318',N'Bạch Long Vĩ',N'Huyện Bạch Long Vĩ',N'Bach Long Vi',N'Bach Long Vi District',N'31'),
	 (N'323',N'Hưng Yên',N'Thành phố Hưng Yên',N'Hung Yen',N'Hung Yen City',N'33'),
	 (N'325',N'Văn Lâm',N'Huyện Văn Lâm',N'Van Lam',N'Van Lam District',N'33'),
	 (N'326',N'Văn Giang',N'Huyện Văn Giang',N'Van Giang',N'Van Giang District',N'33'),
	 (N'327',N'Yên Mỹ',N'Huyện Yên Mỹ',N'Yen My',N'Yen My District',N'33'),
	 (N'328',N'Mỹ Hào',N'Thị xã Mỹ Hào',N'My Hao',N'My Hao Town',N'33'),
	 (N'329',N'Ân Thi',N'Huyện Ân Thi',N'An Thi',N'An Thi District',N'33');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'330',N'Khoái Châu',N'Huyện Khoái Châu',N'Khoai Chau',N'Khoai Chau District',N'33'),
	 (N'331',N'Kim Động',N'Huyện Kim Động',N'Kim Dong',N'Kim Dong District',N'33'),
	 (N'332',N'Tiên Lữ',N'Huyện Tiên Lữ',N'Tien Lu',N'Tien Lu District',N'33'),
	 (N'333',N'Phù Cừ',N'Huyện Phù Cừ',N'Phu Cu',N'Phu Cu District',N'33'),
	 (N'336',N'Thái Bình',N'Thành phố Thái Bình',N'Thai Binh',N'Thai Binh City',N'34'),
	 (N'338',N'Quỳnh Phụ',N'Huyện Quỳnh Phụ',N'Quynh Phu',N'Quynh Phu District',N'34'),
	 (N'339',N'Hưng Hà',N'Huyện Hưng Hà',N'Hung Ha',N'Hung Ha District',N'34'),
	 (N'340',N'Đông Hưng',N'Huyện Đông Hưng',N'Dong Hung',N'Dong Hung District',N'34'),
	 (N'341',N'Thái Thụy',N'Huyện Thái Thụy',N'Thai Thuy',N'Thai Thuy District',N'34'),
	 (N'342',N'Tiền Hải',N'Huyện Tiền Hải',N'Tien Hai',N'Tien Hai District',N'34');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'343',N'Kiến Xương',N'Huyện Kiến Xương',N'Kien Xuong',N'Kien Xuong District',N'34'),
	 (N'344',N'Vũ Thư',N'Huyện Vũ Thư',N'Vu Thu',N'Vu Thu District',N'34'),
	 (N'347',N'Phủ Lý',N'Thành phố Phủ Lý',N'Phu Ly',N'Phu Ly City',N'35'),
	 (N'349',N'Duy Tiên',N'Thị xã Duy Tiên',N'Duy Tien',N'Duy Tien Town',N'35'),
	 (N'350',N'Kim Bảng',N'Huyện Kim Bảng',N'Kim Bang',N'Kim Bang District',N'35'),
	 (N'351',N'Thanh Liêm',N'Huyện Thanh Liêm',N'Thanh Liem',N'Thanh Liem District',N'35'),
	 (N'352',N'Bình Lục',N'Huyện Bình Lục',N'Binh Luc',N'Binh Luc District',N'35'),
	 (N'353',N'Lý Nhân',N'Huyện Lý Nhân',N'Ly Nhan',N'Ly Nhan District',N'35'),
	 (N'356',N'Nam Định',N'Thành phố Nam Định',N'Nam Dinh',N'Nam Dinh City',N'36'),
	 (N'358',N'Mỹ Lộc',N'Huyện Mỹ Lộc',N'My Loc',N'My Loc District',N'36');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'359',N'Vụ Bản',N'Huyện Vụ Bản',N'Vu Ban',N'Vu Ban District',N'36'),
	 (N'360',N'Ý Yên',N'Huyện Ý Yên',N'Y Yen',N'Y Yen District',N'36'),
	 (N'361',N'Nghĩa Hưng',N'Huyện Nghĩa Hưng',N'Nghia Hung',N'Nghia Hung District',N'36'),
	 (N'362',N'Nam Trực',N'Huyện Nam Trực',N'Nam Truc',N'Nam Truc District',N'36'),
	 (N'363',N'Trực Ninh',N'Huyện Trực Ninh',N'Truc Ninh',N'Truc Ninh District',N'36'),
	 (N'364',N'Xuân Trường',N'Huyện Xuân Trường',N'Xuan Truong',N'Xuan Truong District',N'36'),
	 (N'365',N'Giao Thủy',N'Huyện Giao Thủy',N'Giao Thuy',N'Giao Thuy District',N'36'),
	 (N'366',N'Hải Hậu',N'Huyện Hải Hậu',N'Hai Hau',N'Hai Hau District',N'36'),
	 (N'369',N'Ninh Bình',N'Thành phố Ninh Bình',N'Ninh Binh',N'Ninh Binh City',N'37'),
	 (N'370',N'Tam Điệp',N'Thành phố Tam Điệp',N'Tam Diep',N'Tam Diep City',N'37');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'372',N'Nho Quan',N'Huyện Nho Quan',N'Nho Quan',N'Nho Quan District',N'37'),
	 (N'373',N'Gia Viễn',N'Huyện Gia Viễn',N'Gia Vien',N'Gia Vien District',N'37'),
	 (N'374',N'Hoa Lư',N'Huyện Hoa Lư',N'Hoa Lu',N'Hoa Lu District',N'37'),
	 (N'375',N'Yên Khánh',N'Huyện Yên Khánh',N'Yen Khanh',N'Yen Khanh District',N'37'),
	 (N'376',N'Kim Sơn',N'Huyện Kim Sơn',N'Kim Son',N'Kim Son District',N'37'),
	 (N'377',N'Yên Mô',N'Huyện Yên Mô',N'Yen Mo',N'Yen Mo District',N'37'),
	 (N'380',N'Thanh Hóa',N'Thành phố Thanh Hóa',N'Thanh Hoa',N'Thanh Hoa City',N'38'),
	 (N'381',N'Bỉm Sơn',N'Thị xã Bỉm Sơn',N'Bim Son',N'Bim Son Town',N'38'),
	 (N'382',N'Sầm Sơn',N'Thành phố Sầm Sơn',N'Sam Son',N'Sam Son City',N'38'),
	 (N'384',N'Mường Lát',N'Huyện Mường Lát',N'Muong Lat',N'Muong Lat District',N'38');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'385',N'Quan Hóa',N'Huyện Quan Hóa',N'Quan Hoa',N'Quan Hoa District',N'38'),
	 (N'386',N'Bá Thước',N'Huyện Bá Thước',N'Ba Thuoc',N'Ba Thuoc District',N'38'),
	 (N'387',N'Quan Sơn',N'Huyện Quan Sơn',N'Quan Son',N'Quan Son District',N'38'),
	 (N'388',N'Lang Chánh',N'Huyện Lang Chánh',N'Lang Chanh',N'Lang Chanh District',N'38'),
	 (N'389',N'Ngọc Lặc',N'Huyện Ngọc Lặc',N'Ngoc Lac',N'Ngoc Lac District',N'38'),
	 (N'390',N'Cẩm Thủy',N'Huyện Cẩm Thủy',N'Cam Thuy',N'Cam Thuy District',N'38'),
	 (N'391',N'Thạch Thành',N'Huyện Thạch Thành',N'Thach Thanh',N'Thach Thanh District',N'38'),
	 (N'392',N'Hà Trung',N'Huyện Hà Trung',N'Ha Trung',N'Ha Trung District',N'38'),
	 (N'393',N'Vĩnh Lộc',N'Huyện Vĩnh Lộc',N'Vinh Loc',N'Vinh Loc District',N'38'),
	 (N'394',N'Yên Định',N'Huyện Yên Định',N'Yen Dinh',N'Yen Dinh District',N'38');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'395',N'Thọ Xuân',N'Huyện Thọ Xuân',N'Tho Xuan',N'Tho Xuan District',N'38'),
	 (N'396',N'Thường Xuân',N'Huyện Thường Xuân',N'Thuong Xuan',N'Thuong Xuan District',N'38'),
	 (N'397',N'Triệu Sơn',N'Huyện Triệu Sơn',N'Trieu Son',N'Trieu Son District',N'38'),
	 (N'398',N'Thiệu Hóa',N'Huyện Thiệu Hóa',N'Thieu Hoa',N'Thieu Hoa District',N'38'),
	 (N'399',N'Hoằng Hóa',N'Huyện Hoằng Hóa',N'Hoang Hoa',N'Hoang Hoa District',N'38'),
	 (N'400',N'Hậu Lộc',N'Huyện Hậu Lộc',N'Hau Loc',N'Hau Loc District',N'38'),
	 (N'401',N'Nga Sơn',N'Huyện Nga Sơn',N'Nga Son',N'Nga Son District',N'38'),
	 (N'402',N'Như Xuân',N'Huyện Như Xuân',N'Nhu Xuan',N'Nhu Xuan District',N'38'),
	 (N'403',N'Như Thanh',N'Huyện Như Thanh',N'Nhu Thanh',N'Nhu Thanh District',N'38'),
	 (N'404',N'Nông Cống',N'Huyện Nông Cống',N'Nong Cong',N'Nong Cong District',N'38');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'405',N'Đông Sơn',N'Huyện Đông Sơn',N'Dong Son',N'Dong Son District',N'38'),
	 (N'406',N'Quảng Xương',N'Huyện Quảng Xương',N'Quang Xuong',N'Quang Xuong District',N'38'),
	 (N'407',N'Nghi Sơn',N'Thị xã Nghi Sơn',N'Nghi Son',N'Nghi Son Town',N'38'),
	 (N'412',N'Vinh',N'Thành phố Vinh',N'Vinh',N'Vinh City',N'40'),
	 (N'413',N'Cửa Lò',N'Thị xã Cửa Lò',N'Cua Lo',N'Cua Lo Town',N'40'),
	 (N'414',N'Thái Hoà',N'Thị xã Thái Hoà',N'Thai Hoa',N'Thai Hoa Town',N'40'),
	 (N'415',N'Quế Phong',N'Huyện Quế Phong',N'Que Phong',N'Que Phong District',N'40'),
	 (N'416',N'Quỳ Châu',N'Huyện Quỳ Châu',N'Quy Chau',N'Quy Chau District',N'40'),
	 (N'417',N'Kỳ Sơn',N'Huyện Kỳ Sơn',N'Ky Son',N'Ky Son District',N'40'),
	 (N'418',N'Tương Dương',N'Huyện Tương Dương',N'Tuong Duong',N'Tuong Duong District',N'40');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'419',N'Nghĩa Đàn',N'Huyện Nghĩa Đàn',N'Nghia Dan',N'Nghia Dan District',N'40'),
	 (N'420',N'Quỳ Hợp',N'Huyện Quỳ Hợp',N'Quy Hop',N'Quy Hop District',N'40'),
	 (N'421',N'Quỳnh Lưu',N'Huyện Quỳnh Lưu',N'Quynh Luu',N'Quynh Luu District',N'40'),
	 (N'422',N'Con Cuông',N'Huyện Con Cuông',N'Con Cuong',N'Con Cuong District',N'40'),
	 (N'423',N'Tân Kỳ',N'Huyện Tân Kỳ',N'Tan Ky',N'Tan Ky District',N'40'),
	 (N'424',N'Anh Sơn',N'Huyện Anh Sơn',N'Anh Son',N'Anh Son District',N'40'),
	 (N'425',N'Diễn Châu',N'Huyện Diễn Châu',N'Dien Chau',N'Dien Chau District',N'40'),
	 (N'426',N'Yên Thành',N'Huyện Yên Thành',N'Yen Thanh',N'Yen Thanh District',N'40'),
	 (N'427',N'Đô Lương',N'Huyện Đô Lương',N'Do Luong',N'Do Luong District',N'40'),
	 (N'428',N'Thanh Chương',N'Huyện Thanh Chương',N'Thanh Chuong',N'Thanh Chuong District',N'40');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'429',N'Nghi Lộc',N'Huyện Nghi Lộc',N'Nghi Loc',N'Nghi Loc District',N'40'),
	 (N'430',N'Nam Đàn',N'Huyện Nam Đàn',N'Nam Dan',N'Nam Dan District',N'40'),
	 (N'431',N'Hưng Nguyên',N'Huyện Hưng Nguyên',N'Hung Nguyen',N'Hung Nguyen District',N'40'),
	 (N'432',N'Hoàng Mai',N'Thị xã Hoàng Mai',N'Hoang Mai',N'Hoang Mai Town',N'40'),
	 (N'436',N'Hà Tĩnh',N'Thành phố Hà Tĩnh',N'Ha Tinh',N'Ha Tinh City',N'42'),
	 (N'437',N'Hồng Lĩnh',N'Thị xã Hồng Lĩnh',N'Hong Linh',N'Hong Linh Town',N'42'),
	 (N'439',N'Hương Sơn',N'Huyện Hương Sơn',N'Huong Son',N'Huong Son District',N'42'),
	 (N'440',N'Đức Thọ',N'Huyện Đức Thọ',N'Duc Tho',N'Duc Tho District',N'42'),
	 (N'441',N'Vũ Quang',N'Huyện Vũ Quang',N'Vu Quang',N'Vu Quang District',N'42'),
	 (N'442',N'Nghi Xuân',N'Huyện Nghi Xuân',N'Nghi Xuan',N'Nghi Xuan District',N'42');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'443',N'Can Lộc',N'Huyện Can Lộc',N'Can Loc',N'Can Loc District',N'42'),
	 (N'444',N'Hương Khê',N'Huyện Hương Khê',N'Huong Khe',N'Huong Khe District',N'42'),
	 (N'445',N'Thạch Hà',N'Huyện Thạch Hà',N'Thach Ha',N'Thach Ha District',N'42'),
	 (N'446',N'Cẩm Xuyên',N'Huyện Cẩm Xuyên',N'Cam Xuyen',N'Cam Xuyen District',N'42'),
	 (N'447',N'Kỳ Anh',N'Huyện Kỳ Anh',N'Ky Anh',N'Ky Anh District',N'42'),
	 (N'448',N'Lộc Hà',N'Huyện Lộc Hà',N'Loc Ha',N'Loc Ha District',N'42'),
	 (N'449',N'Kỳ Anh',N'Thị xã Kỳ Anh',N'Ky Anh',N'Ky Anh Town',N'42'),
	 (N'450',N'Đồng Hới',N'Thành phố Đồng Hới',N'Dong Hoi',N'Dong Hoi City',N'44'),
	 (N'452',N'Minh Hóa',N'Huyện Minh Hóa',N'Minh Hoa',N'Minh Hoa District',N'44'),
	 (N'453',N'Tuyên Hóa',N'Huyện Tuyên Hóa',N'Tuyen Hoa',N'Tuyen Hoa District',N'44');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'454',N'Quảng Trạch',N'Huyện Quảng Trạch',N'Quang Trach',N'Quang Trach District',N'44'),
	 (N'455',N'Bố Trạch',N'Huyện Bố Trạch',N'Bo Trach',N'Bo Trach District',N'44'),
	 (N'456',N'Quảng Ninh',N'Huyện Quảng Ninh',N'Quang Ninh',N'Quang Ninh District',N'44'),
	 (N'457',N'Lệ Thủy',N'Huyện Lệ Thủy',N'Le Thuy',N'Le Thuy District',N'44'),
	 (N'458',N'Ba Đồn',N'Thị xã Ba Đồn',N'Ba Don',N'Ba Don Town',N'44'),
	 (N'461',N'Đông Hà',N'Thành phố Đông Hà',N'Dong Ha',N'Dong Ha City',N'45'),
	 (N'462',N'Quảng Trị',N'Thị xã Quảng Trị',N'Quang Tri',N'Quang Tri Town',N'45'),
	 (N'464',N'Vĩnh Linh',N'Huyện Vĩnh Linh',N'Vinh Linh',N'Vinh Linh District',N'45'),
	 (N'465',N'Hướng Hóa',N'Huyện Hướng Hóa',N'Huong Hoa',N'Huong Hoa District',N'45'),
	 (N'466',N'Gio Linh',N'Huyện Gio Linh',N'Gio Linh',N'Gio Linh District',N'45');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'467',N'Đa Krông',N'Huyện Đa Krông',N'Da Krong',N'Da Krong District',N'45'),
	 (N'468',N'Cam Lộ',N'Huyện Cam Lộ',N'Cam Lo',N'Cam Lo District',N'45'),
	 (N'469',N'Triệu Phong',N'Huyện Triệu Phong',N'Trieu Phong',N'Trieu Phong District',N'45'),
	 (N'470',N'Hải Lăng',N'Huyện Hải Lăng',N'Hai Lang',N'Hai Lang District',N'45'),
	 (N'471',N'Cồn Cỏ',N'Huyện Cồn Cỏ',N'Con Co',N'Con Co District',N'45'),
	 (N'474',N'Huế',N'Thành phố Huế',N'Hue',N'Hue City',N'46'),
	 (N'476',N'Phong Điền',N'Huyện Phong Điền',N'Phong Dien',N'Phong Dien District',N'46'),
	 (N'477',N'Quảng Điền',N'Huyện Quảng Điền',N'Quang Dien',N'Quang Dien District',N'46'),
	 (N'478',N'Phú Vang',N'Huyện Phú Vang',N'Phu Vang',N'Phu Vang District',N'46'),
	 (N'479',N'Hương Thủy',N'Thị xã Hương Thủy',N'Huong Thuy',N'Huong Thuy Town',N'46');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'480',N'Hương Trà',N'Thị xã Hương Trà',N'Huong Tra',N'Huong Tra Town',N'46'),
	 (N'481',N'A Lưới',N'Huyện A Lưới',N'A Luoi',N'A Luoi District',N'46'),
	 (N'482',N'Phú Lộc',N'Huyện Phú Lộc',N'Phu Loc',N'Phu Loc District',N'46'),
	 (N'483',N'Nam Đông',N'Huyện Nam Đông',N'Nam Dong',N'Nam Dong District',N'46'),
	 (N'490',N'Liên Chiểu',N'Quận Liên Chiểu',N'Lien Chieu',N'Lien Chieu District',N'48'),
	 (N'491',N'Thanh Khê',N'Quận Thanh Khê',N'Thanh Khe',N'Thanh Khe District',N'48'),
	 (N'492',N'Hải Châu',N'Quận Hải Châu',N'Hai Chau',N'Hai Chau District',N'48'),
	 (N'493',N'Sơn Trà',N'Quận Sơn Trà',N'Son Tra',N'Son Tra District',N'48'),
	 (N'494',N'Ngũ Hành Sơn',N'Quận Ngũ Hành Sơn',N'Ngu Hanh Son',N'Ngu Hanh Son District',N'48'),
	 (N'495',N'Cẩm Lệ',N'Quận Cẩm Lệ',N'Cam Le',N'Cam Le District',N'48');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'497',N'Hòa Vang',N'Huyện Hòa Vang',N'Hoa Vang',N'Hoa Vang District',N'48'),
	 (N'498',N'Hoàng Sa',N'Huyện Hoàng Sa',N'Hoang Sa',N'Hoang Sa District',N'48'),
	 (N'502',N'Tam Kỳ',N'Thành phố Tam Kỳ',N'Tam Ky',N'Tam Ky City',N'49'),
	 (N'503',N'Hội An',N'Thành phố Hội An',N'Hoi An',N'Hoi An City',N'49'),
	 (N'504',N'Tây Giang',N'Huyện Tây Giang',N'Tay Giang',N'Tay Giang District',N'49'),
	 (N'505',N'Đông Giang',N'Huyện Đông Giang',N'Dong Giang',N'Dong Giang District',N'49'),
	 (N'506',N'Đại Lộc',N'Huyện Đại Lộc',N'Dai Loc',N'Dai Loc District',N'49'),
	 (N'507',N'Điện Bàn',N'Thị xã Điện Bàn',N'Dien Ban',N'Dien Ban Town',N'49'),
	 (N'508',N'Duy Xuyên',N'Huyện Duy Xuyên',N'Duy Xuyen',N'Duy Xuyen District',N'49'),
	 (N'509',N'Quế Sơn',N'Huyện Quế Sơn',N'Que Son',N'Que Son District',N'49');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'510',N'Nam Giang',N'Huyện Nam Giang',N'Nam Giang',N'Nam Giang District',N'49'),
	 (N'511',N'Phước Sơn',N'Huyện Phước Sơn',N'Phuoc Son',N'Phuoc Son District',N'49'),
	 (N'512',N'Hiệp Đức',N'Huyện Hiệp Đức',N'Hiep Duc',N'Hiep Duc District',N'49'),
	 (N'513',N'Thăng Bình',N'Huyện Thăng Bình',N'Thang Binh',N'Thang Binh District',N'49'),
	 (N'514',N'Tiên Phước',N'Huyện Tiên Phước',N'Tien Phuoc',N'Tien Phuoc District',N'49'),
	 (N'515',N'Bắc Trà My',N'Huyện Bắc Trà My',N'Bac Tra My',N'Bac Tra My District',N'49'),
	 (N'516',N'Nam Trà My',N'Huyện Nam Trà My',N'Nam Tra My',N'Nam Tra My District',N'49'),
	 (N'517',N'Núi Thành',N'Huyện Núi Thành',N'Nui Thanh',N'Nui Thanh District',N'49'),
	 (N'518',N'Phú Ninh',N'Huyện Phú Ninh',N'Phu Ninh',N'Phu Ninh District',N'49'),
	 (N'519',N'Nông Sơn',N'Huyện Nông Sơn',N'Nong Son',N'Nong Son District',N'49');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'522',N'Quảng Ngãi',N'Thành phố Quảng Ngãi',N'Quang Ngai',N'Quang Ngai City',N'51'),
	 (N'524',N'Bình Sơn',N'Huyện Bình Sơn',N'Binh Son',N'Binh Son District',N'51'),
	 (N'525',N'Trà Bồng',N'Huyện Trà Bồng',N'Tra Bong',N'Tra Bong District',N'51'),
	 (N'527',N'Sơn Tịnh',N'Huyện Sơn Tịnh',N'Son Tinh',N'Son Tinh District',N'51'),
	 (N'528',N'Tư Nghĩa',N'Huyện Tư Nghĩa',N'Tu Nghia',N'Tu Nghia District',N'51'),
	 (N'529',N'Sơn Hà',N'Huyện Sơn Hà',N'Son Ha',N'Son Ha District',N'51'),
	 (N'530',N'Sơn Tây',N'Huyện Sơn Tây',N'Son Tay',N'Son Tay District',N'51'),
	 (N'531',N'Minh Long',N'Huyện Minh Long',N'Minh Long',N'Minh Long District',N'51'),
	 (N'532',N'Nghĩa Hành',N'Huyện Nghĩa Hành',N'Nghia Hanh',N'Nghia Hanh District',N'51'),
	 (N'533',N'Mộ Đức',N'Huyện Mộ Đức',N'Mo Duc',N'Mo Duc District',N'51');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'534',N'Đức Phổ',N'Thị xã Đức Phổ',N'Duc Pho',N'Duc Pho Town',N'51'),
	 (N'535',N'Ba Tơ',N'Huyện Ba Tơ',N'Ba To',N'Ba To District',N'51'),
	 (N'536',N'Lý Sơn',N'Huyện Lý Sơn',N'Ly Son',N'Ly Son District',N'51'),
	 (N'540',N'Quy Nhơn',N'Thành phố Quy Nhơn',N'Quy Nhon',N'Quy Nhon City',N'52'),
	 (N'542',N'An Lão',N'Huyện An Lão',N'An Lao',N'An Lao District',N'52'),
	 (N'543',N'Hoài Nhơn',N'Thị xã Hoài Nhơn',N'Hoai Nhon',N'Hoai Nhon Town',N'52'),
	 (N'544',N'Hoài Ân',N'Huyện Hoài Ân',N'Hoai An',N'Hoai An District',N'52'),
	 (N'545',N'Phù Mỹ',N'Huyện Phù Mỹ',N'Phu My',N'Phu My District',N'52'),
	 (N'546',N'Vĩnh Thạnh',N'Huyện Vĩnh Thạnh',N'Vinh Thanh',N'Vinh Thanh District',N'52'),
	 (N'547',N'Tây Sơn',N'Huyện Tây Sơn',N'Tay Son',N'Tay Son District',N'52');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'548',N'Phù Cát',N'Huyện Phù Cát',N'Phu Cat',N'Phu Cat District',N'52'),
	 (N'549',N'An Nhơn',N'Thị xã An Nhơn',N'An Nhon',N'An Nhon Town',N'52'),
	 (N'550',N'Tuy Phước',N'Huyện Tuy Phước',N'Tuy Phuoc',N'Tuy Phuoc District',N'52'),
	 (N'551',N'Vân Canh',N'Huyện Vân Canh',N'Van Canh',N'Van Canh District',N'52'),
	 (N'555',N'Tuy Hoà',N'Thành phố Tuy Hoà',N'Tuy Hoa',N'Tuy Hoa City',N'54'),
	 (N'557',N'Sông Cầu',N'Thị xã Sông Cầu',N'Song Cau',N'Song Cau Town',N'54'),
	 (N'558',N'Đồng Xuân',N'Huyện Đồng Xuân',N'Dong Xuan',N'Dong Xuan District',N'54'),
	 (N'559',N'Tuy An',N'Huyện Tuy An',N'Tuy An',N'Tuy An District',N'54'),
	 (N'560',N'Sơn Hòa',N'Huyện Sơn Hòa',N'Son Hoa',N'Son Hoa District',N'54'),
	 (N'561',N'Sông Hinh',N'Huyện Sông Hinh',N'Song Hinh',N'Song Hinh District',N'54');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'562',N'Tây Hoà',N'Huyện Tây Hoà',N'Tay Hoa',N'Tay Hoa District',N'54'),
	 (N'563',N'Phú Hoà',N'Huyện Phú Hoà',N'Phu Hoa',N'Phu Hoa District',N'54'),
	 (N'564',N'Đông Hòa',N'Thị xã Đông Hòa',N'Dong Hoa',N'Dong Hoa Town',N'54'),
	 (N'568',N'Nha Trang',N'Thành phố Nha Trang',N'Nha Trang',N'Nha Trang City',N'56'),
	 (N'569',N'Cam Ranh',N'Thành phố Cam Ranh',N'Cam Ranh',N'Cam Ranh City',N'56'),
	 (N'570',N'Cam Lâm',N'Huyện Cam Lâm',N'Cam Lam',N'Cam Lam District',N'56'),
	 (N'571',N'Vạn Ninh',N'Huyện Vạn Ninh',N'Van Ninh',N'Van Ninh District',N'56'),
	 (N'572',N'Ninh Hòa',N'Thị xã Ninh Hòa',N'Ninh Hoa',N'Ninh Hoa Town',N'56'),
	 (N'573',N'Khánh Vĩnh',N'Huyện Khánh Vĩnh',N'Khanh Vinh',N'Khanh Vinh District',N'56'),
	 (N'574',N'Diên Khánh',N'Huyện Diên Khánh',N'Dien Khanh',N'Dien Khanh District',N'56');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'575',N'Khánh Sơn',N'Huyện Khánh Sơn',N'Khanh Son',N'Khanh Son District',N'56'),
	 (N'576',N'Trường Sa',N'Huyện Trường Sa',N'Truong Sa',N'Truong Sa District',N'56'),
	 (N'582',N'Phan Rang-Tháp Chàm',N'Thành phố Phan Rang-Tháp Chàm',N'Phan Rang-Thap Cham',N'Phan Rang-Thap Cham City',N'58'),
	 (N'584',N'Bác Ái',N'Huyện Bác Ái',N'Bac Ai',N'Bac Ai District',N'58'),
	 (N'585',N'Ninh Sơn',N'Huyện Ninh Sơn',N'Ninh Son',N'Ninh Son District',N'58'),
	 (N'586',N'Ninh Hải',N'Huyện Ninh Hải',N'Ninh Hai',N'Ninh Hai District',N'58'),
	 (N'587',N'Ninh Phước',N'Huyện Ninh Phước',N'Ninh Phuoc',N'Ninh Phuoc District',N'58'),
	 (N'588',N'Thuận Bắc',N'Huyện Thuận Bắc',N'Thuan Bac',N'Thuan Bac District',N'58'),
	 (N'589',N'Thuận Nam',N'Huyện Thuận Nam',N'Thuan Nam',N'Thuan Nam District',N'58'),
	 (N'593',N'Phan Thiết',N'Thành phố Phan Thiết',N'Phan Thiet',N'Phan Thiet City',N'60');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'594',N'La Gi',N'Thị xã La Gi',N'La Gi',N'La Gi Town',N'60'),
	 (N'595',N'Tuy Phong',N'Huyện Tuy Phong',N'Tuy Phong',N'Tuy Phong District',N'60'),
	 (N'596',N'Bắc Bình',N'Huyện Bắc Bình',N'Bac Binh',N'Bac Binh District',N'60'),
	 (N'597',N'Hàm Thuận Bắc',N'Huyện Hàm Thuận Bắc',N'Ham Thuan Bac',N'Ham Thuan Bac District',N'60'),
	 (N'598',N'Hàm Thuận Nam',N'Huyện Hàm Thuận Nam',N'Ham Thuan Nam',N'Ham Thuan Nam District',N'60'),
	 (N'599',N'Tánh Linh',N'Huyện Tánh Linh',N'Tanh Linh',N'Tanh Linh District',N'60'),
	 (N'600',N'Đức Linh',N'Huyện Đức Linh',N'Duc Linh',N'Duc Linh District',N'60'),
	 (N'601',N'Hàm Tân',N'Huyện Hàm Tân',N'Ham Tan',N'Ham Tan District',N'60'),
	 (N'602',N'Phú Quí',N'Huyện Phú Quí',N'Phu Qui',N'Phu Qui District',N'60'),
	 (N'608',N'Kon Tum',N'Thành phố Kon Tum',N'Kon Tum',N'Kon Tum City',N'62');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'610',N'Đắk Glei',N'Huyện Đắk Glei',N'Dak Glei',N'Dak Glei District',N'62'),
	 (N'611',N'Ngọc Hồi',N'Huyện Ngọc Hồi',N'Ngoc Hoi',N'Ngoc Hoi District',N'62'),
	 (N'612',N'Đắk Tô',N'Huyện Đắk Tô',N'Dak To',N'Dak To District',N'62'),
	 (N'613',N'Kon Plông',N'Huyện Kon Plông',N'Kon Plong',N'Kon Plong District',N'62'),
	 (N'614',N'Kon Rẫy',N'Huyện Kon Rẫy',N'Kon Ray',N'Kon Ray District',N'62'),
	 (N'615',N'Đắk Hà',N'Huyện Đắk Hà',N'Dak Ha',N'Dak Ha District',N'62'),
	 (N'616',N'Sa Thầy',N'Huyện Sa Thầy',N'Sa Thay',N'Sa Thay District',N'62'),
	 (N'617',N'Tu Mơ Rông',N'Huyện Tu Mơ Rông',N'Tu Mo Rong',N'Tu Mo Rong District',N'62'),
	 (N'618',N'Ia H'' Drai',N'Huyện Ia H'' Drai',N'Ia H'' Drai',N'Ia H'' Drai District',N'62'),
	 (N'622',N'Pleiku',N'Thành phố Pleiku',N'Pleiku',N'Pleiku City',N'64');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'623',N'An Khê',N'Thị xã An Khê',N'An Khe',N'An Khe Town',N'64'),
	 (N'624',N'Ayun Pa',N'Thị xã Ayun Pa',N'Ayun Pa',N'Ayun Pa Town',N'64'),
	 (N'625',N'KBang',N'Huyện KBang',N'KBang',N'KBang District',N'64'),
	 (N'626',N'Đăk Đoa',N'Huyện Đăk Đoa',N'Dak Doa',N'Dak Doa District',N'64'),
	 (N'627',N'Chư Păh',N'Huyện Chư Păh',N'Chu Pah',N'Chu Pah District',N'64'),
	 (N'628',N'Ia Grai',N'Huyện Ia Grai',N'Ia Grai',N'Ia Grai District',N'64'),
	 (N'629',N'Mang Yang',N'Huyện Mang Yang',N'Mang Yang',N'Mang Yang District',N'64'),
	 (N'630',N'Kông Chro',N'Huyện Kông Chro',N'Kong Chro',N'Kong Chro District',N'64'),
	 (N'631',N'Đức Cơ',N'Huyện Đức Cơ',N'Duc Co',N'Duc Co District',N'64'),
	 (N'632',N'Chư Prông',N'Huyện Chư Prông',N'Chu Prong',N'Chu Prong District',N'64');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'633',N'Chư Sê',N'Huyện Chư Sê',N'Chu Se',N'Chu Se District',N'64'),
	 (N'634',N'Đăk Pơ',N'Huyện Đăk Pơ',N'Dak Po',N'Dak Po District',N'64'),
	 (N'635',N'Ia Pa',N'Huyện Ia Pa',N'Ia Pa',N'Ia Pa District',N'64'),
	 (N'637',N'Krông Pa',N'Huyện Krông Pa',N'Krong Pa',N'Krong Pa District',N'64'),
	 (N'638',N'Phú Thiện',N'Huyện Phú Thiện',N'Phu Thien',N'Phu Thien District',N'64'),
	 (N'639',N'Chư Pưh',N'Huyện Chư Pưh',N'Chu Puh',N'Chu Puh District',N'64'),
	 (N'643',N'Buôn Ma Thuột',N'Thành phố Buôn Ma Thuột',N'Buon Ma Thuot',N'Buon Ma Thuot City',N'66'),
	 (N'644',N'Buôn Hồ',N'Thị xã Buôn Hồ',N'Buon Ho',N'Buon Ho Town',N'66'),
	 (N'645',N'Ea H''leo',N'Huyện Ea H''leo',N'Ea H''leo',N'Ea H''leo District',N'66'),
	 (N'646',N'Ea Súp',N'Huyện Ea Súp',N'Ea Sup',N'Ea Sup District',N'66');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'647',N'Buôn Đôn',N'Huyện Buôn Đôn',N'Buon Don',N'Buon Don District',N'66'),
	 (N'648',N'Cư M''gar',N'Huyện Cư M''gar',N'Cu M''gar',N'Cu M''gar District',N'66'),
	 (N'649',N'Krông Búk',N'Huyện Krông Búk',N'Krong Buk',N'Krong Buk District',N'66'),
	 (N'650',N'Krông Năng',N'Huyện Krông Năng',N'Krong Nang',N'Krong Nang District',N'66'),
	 (N'651',N'Ea Kar',N'Huyện Ea Kar',N'Ea Kar',N'Ea Kar District',N'66'),
	 (N'652',N'M''Đrắk',N'Huyện M''Đrắk',N'M''Drak',N'M''Drak District',N'66'),
	 (N'653',N'Krông Bông',N'Huyện Krông Bông',N'Krong Bong',N'Krong Bong District',N'66'),
	 (N'654',N'Krông Pắc',N'Huyện Krông Pắc',N'Krong Pac',N'Krong Pac District',N'66'),
	 (N'655',N'Krông A Na',N'Huyện Krông A Na',N'Krong A Na',N'Krong A Na District',N'66'),
	 (N'656',N'Lắk',N'Huyện Lắk',N'Lak',N'Lak District',N'66');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'657',N'Cư Kuin',N'Huyện Cư Kuin',N'Cu Kuin',N'Cu Kuin District',N'66'),
	 (N'660',N'Gia Nghĩa',N'Thành phố Gia Nghĩa',N'Gia Nghia',N'Gia Nghia City',N'67'),
	 (N'661',N'Đăk Glong',N'Huyện Đăk Glong',N'Dak Glong',N'Dak Glong District',N'67'),
	 (N'662',N'Cư Jút',N'Huyện Cư Jút',N'Cu Jut',N'Cu Jut District',N'67'),
	 (N'663',N'Đắk Mil',N'Huyện Đắk Mil',N'Dak Mil',N'Dak Mil District',N'67'),
	 (N'664',N'Krông Nô',N'Huyện Krông Nô',N'Krong No',N'Krong No District',N'67'),
	 (N'665',N'Đắk Song',N'Huyện Đắk Song',N'Dak Song',N'Dak Song District',N'67'),
	 (N'666',N'Đắk R''Lấp',N'Huyện Đắk R''Lấp',N'Dak R''Lap',N'Dak R''Lap District',N'67'),
	 (N'667',N'Tuy Đức',N'Huyện Tuy Đức',N'Tuy Duc',N'Tuy Duc District',N'67'),
	 (N'672',N'Đà Lạt',N'Thành phố Đà Lạt',N'Da Lat',N'Da Lat City',N'68');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'673',N'Bảo Lộc',N'Thành phố Bảo Lộc',N'Bao Loc',N'Bao Loc City',N'68'),
	 (N'674',N'Đam Rông',N'Huyện Đam Rông',N'Dam Rong',N'Dam Rong District',N'68'),
	 (N'675',N'Lạc Dương',N'Huyện Lạc Dương',N'Lac Duong',N'Lac Duong District',N'68'),
	 (N'676',N'Lâm Hà',N'Huyện Lâm Hà',N'Lam Ha',N'Lam Ha District',N'68'),
	 (N'677',N'Đơn Dương',N'Huyện Đơn Dương',N'Don Duong',N'Don Duong District',N'68'),
	 (N'678',N'Đức Trọng',N'Huyện Đức Trọng',N'Duc Trong',N'Duc Trong District',N'68'),
	 (N'679',N'Di Linh',N'Huyện Di Linh',N'Di Linh',N'Di Linh District',N'68'),
	 (N'680',N'Bảo Lâm',N'Huyện Bảo Lâm',N'Bao Lam',N'Bao Lam District',N'68'),
	 (N'681',N'Đạ Huoai',N'Huyện Đạ Huoai',N'Da Huoai',N'Da Huoai District',N'68'),
	 (N'682',N'Đạ Tẻh',N'Huyện Đạ Tẻh',N'Da Teh',N'Da Teh District',N'68');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'683',N'Cát Tiên',N'Huyện Cát Tiên',N'Cat Tien',N'Cat Tien District',N'68'),
	 (N'688',N'Phước Long',N'Thị xã Phước Long',N'Phuoc Long',N'Phuoc Long Town',N'70'),
	 (N'689',N'Đồng Xoài',N'Thành phố Đồng Xoài',N'Dong Xoai',N'Dong Xoai City',N'70'),
	 (N'690',N'Bình Long',N'Thị xã Bình Long',N'Binh Long',N'Binh Long Town',N'70'),
	 (N'691',N'Bù Gia Mập',N'Huyện Bù Gia Mập',N'Bu Gia Map',N'Bu Gia Map District',N'70'),
	 (N'692',N'Lộc Ninh',N'Huyện Lộc Ninh',N'Loc Ninh',N'Loc Ninh District',N'70'),
	 (N'693',N'Bù Đốp',N'Huyện Bù Đốp',N'Bu Dop',N'Bu Dop District',N'70'),
	 (N'694',N'Hớn Quản',N'Huyện Hớn Quản',N'Hon Quan',N'Hon Quan District',N'70'),
	 (N'695',N'Đồng Phú',N'Huyện Đồng Phú',N'Dong Phu',N'Dong Phu District',N'70'),
	 (N'696',N'Bù Đăng',N'Huyện Bù Đăng',N'Bu Dang',N'Bu Dang District',N'70');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'697',N'Chơn Thành',N'Thị xã Chơn Thành',N'Chon Thanh',N'Chon Thanh Town',N'70'),
	 (N'698',N'Phú Riềng',N'Huyện Phú Riềng',N'Phu Rieng',N'Phu Rieng District',N'70'),
	 (N'703',N'Tây Ninh',N'Thành phố Tây Ninh',N'Tay Ninh',N'Tay Ninh City',N'72'),
	 (N'705',N'Tân Biên',N'Huyện Tân Biên',N'Tan Bien',N'Tan Bien District',N'72'),
	 (N'706',N'Tân Châu',N'Huyện Tân Châu',N'Tan Chau',N'Tan Chau District',N'72'),
	 (N'707',N'Dương Minh Châu',N'Huyện Dương Minh Châu',N'Duong Minh Chau',N'Duong Minh Chau District',N'72'),
	 (N'708',N'Châu Thành',N'Huyện Châu Thành',N'Chau Thanh',N'Chau Thanh District',N'72'),
	 (N'709',N'Hòa Thành',N'Thị xã Hòa Thành',N'Hoa Thanh',N'Hoa Thanh Town',N'72'),
	 (N'710',N'Gò Dầu',N'Huyện Gò Dầu',N'Go Dau',N'Go Dau District',N'72'),
	 (N'711',N'Bến Cầu',N'Huyện Bến Cầu',N'Ben Cau',N'Ben Cau District',N'72');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'712',N'Trảng Bàng',N'Thị xã Trảng Bàng',N'Trang Bang',N'Trang Bang Town',N'72'),
	 (N'718',N'Thủ Dầu Một',N'Thành phố Thủ Dầu Một',N'Thu Dau Mot',N'Thu Dau Mot City',N'74'),
	 (N'719',N'Bàu Bàng',N'Huyện Bàu Bàng',N'Bau Bang',N'Bau Bang District',N'74'),
	 (N'720',N'Dầu Tiếng',N'Huyện Dầu Tiếng',N'Dau Tieng',N'Dau Tieng District',N'74'),
	 (N'721',N'Bến Cát',N'Thị xã Bến Cát',N'Ben Cat',N'Ben Cat Town',N'74'),
	 (N'722',N'Phú Giáo',N'Huyện Phú Giáo',N'Phu Giao',N'Phu Giao District',N'74'),
	 (N'723',N'Tân Uyên',N'Thành phố Tân Uyên',N'Tan Uyen',N'Tan Uyen City',N'74'),
	 (N'724',N'Dĩ An',N'Thành phố Dĩ An',N'Di An',N'Di An City',N'74'),
	 (N'725',N'Thuận An',N'Thành phố Thuận An',N'Thuan An',N'Thuan An City',N'74'),
	 (N'726',N'Bắc Tân Uyên',N'Huyện Bắc Tân Uyên',N'Bac Tan Uyen',N'Bac Tan Uyen District',N'74');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'731',N'Biên Hòa',N'Thành phố Biên Hòa',N'Bien Hoa',N'Bien Hoa City',N'75'),
	 (N'732',N'Long Khánh',N'Thành phố Long Khánh',N'Long Khanh',N'Long Khanh City',N'75'),
	 (N'734',N'Tân Phú',N'Huyện Tân Phú',N'Tan Phu',N'Tan Phu District',N'75'),
	 (N'735',N'Vĩnh Cửu',N'Huyện Vĩnh Cửu',N'Vinh Cuu',N'Vinh Cuu District',N'75'),
	 (N'736',N'Định Quán',N'Huyện Định Quán',N'Dinh Quan',N'Dinh Quan District',N'75'),
	 (N'737',N'Trảng Bom',N'Huyện Trảng Bom',N'Trang Bom',N'Trang Bom District',N'75'),
	 (N'738',N'Thống Nhất',N'Huyện Thống Nhất',N'Thong Nhat',N'Thong Nhat District',N'75'),
	 (N'739',N'Cẩm Mỹ',N'Huyện Cẩm Mỹ',N'Cam My',N'Cam My District',N'75'),
	 (N'740',N'Long Thành',N'Huyện Long Thành',N'Long Thanh',N'Long Thanh District',N'75'),
	 (N'741',N'Xuân Lộc',N'Huyện Xuân Lộc',N'Xuan Loc',N'Xuan Loc District',N'75');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'742',N'Nhơn Trạch',N'Huyện Nhơn Trạch',N'Nhon Trach',N'Nhon Trach District',N'75'),
	 (N'747',N'Vũng Tàu',N'Thành phố Vũng Tàu',N'Vung Tau',N'Vung Tau City',N'77'),
	 (N'748',N'Bà Rịa',N'Thành phố Bà Rịa',N'Ba Ria',N'Ba Ria City',N'77'),
	 (N'750',N'Châu Đức',N'Huyện Châu Đức',N'Chau Duc',N'Chau Duc District',N'77'),
	 (N'751',N'Xuyên Mộc',N'Huyện Xuyên Mộc',N'Xuyen Moc',N'Xuyen Moc District',N'77'),
	 (N'752',N'Long Điền',N'Huyện Long Điền',N'Long Dien',N'Long Dien District',N'77'),
	 (N'753',N'Đất Đỏ',N'Huyện Đất Đỏ',N'Dat Do',N'Dat Do District',N'77'),
	 (N'754',N'Phú Mỹ',N'Thị xã Phú Mỹ',N'Phu My',N'Phu My Town',N'77'),
	 (N'755',N'Côn Đảo',N'Huyện Côn Đảo',N'Con Dao',N'Con Dao District',N'77'),
	 (N'794',N'Tân An',N'Thành phố Tân An',N'Tan An',N'Tan An City',N'80');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'795',N'Kiến Tường',N'Thị xã Kiến Tường',N'Kien Tuong',N'Kien Tuong Town',N'80'),
	 (N'796',N'Tân Hưng',N'Huyện Tân Hưng',N'Tan Hung',N'Tan Hung District',N'80'),
	 (N'797',N'Vĩnh Hưng',N'Huyện Vĩnh Hưng',N'Vinh Hung',N'Vinh Hung District',N'80'),
	 (N'798',N'Mộc Hóa',N'Huyện Mộc Hóa',N'Moc Hoa',N'Moc Hoa District',N'80'),
	 (N'799',N'Tân Thạnh',N'Huyện Tân Thạnh',N'Tan Thanh',N'Tan Thanh District',N'80'),
	 (N'800',N'Thạnh Hóa',N'Huyện Thạnh Hóa',N'Thanh Hoa',N'Thanh Hoa District',N'80'),
	 (N'801',N'Đức Huệ',N'Huyện Đức Huệ',N'Duc Hue',N'Duc Hue District',N'80'),
	 (N'802',N'Đức Hòa',N'Huyện Đức Hòa',N'Duc Hoa',N'Duc Hoa District',N'80'),
	 (N'803',N'Bến Lức',N'Huyện Bến Lức',N'Ben Luc',N'Ben Luc District',N'80'),
	 (N'804',N'Thủ Thừa',N'Huyện Thủ Thừa',N'Thu Thua',N'Thu Thua District',N'80');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'805',N'Tân Trụ',N'Huyện Tân Trụ',N'Tan Tru',N'Tan Tru District',N'80'),
	 (N'806',N'Cần Đước',N'Huyện Cần Đước',N'Can Duoc',N'Can Duoc District',N'80'),
	 (N'807',N'Cần Giuộc',N'Huyện Cần Giuộc',N'Can Giuoc',N'Can Giuoc District',N'80'),
	 (N'808',N'Châu Thành',N'Huyện Châu Thành',N'Chau Thanh',N'Chau Thanh District',N'80'),
	 (N'815',N'Mỹ Tho',N'Thành phố Mỹ Tho',N'My Tho',N'My Tho City',N'82'),
	 (N'816',N'Gò Công',N'Thị xã Gò Công',N'Go Cong',N'Go Cong Town',N'82'),
	 (N'817',N'Cai Lậy',N'Thị xã Cai Lậy',N'Cai Lay',N'Cai Lay Town',N'82'),
	 (N'818',N'Tân Phước',N'Huyện Tân Phước',N'Tan Phuoc',N'Tan Phuoc District',N'82'),
	 (N'819',N'Cái Bè',N'Huyện Cái Bè',N'Cai Be',N'Cai Be District',N'82'),
	 (N'820',N'Cai Lậy',N'Huyện Cai Lậy',N'Cai Lay',N'Cai Lay District',N'82');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'821',N'Châu Thành',N'Huyện Châu Thành',N'Chau Thanh',N'Chau Thanh District',N'82'),
	 (N'822',N'Chợ Gạo',N'Huyện Chợ Gạo',N'Cho Gao',N'Cho Gao District',N'82'),
	 (N'823',N'Gò Công Tây',N'Huyện Gò Công Tây',N'Go Cong Tay',N'Go Cong Tay District',N'82'),
	 (N'824',N'Gò Công Đông',N'Huyện Gò Công Đông',N'Go Cong Dong',N'Go Cong Dong District',N'82'),
	 (N'825',N'Tân Phú Đông',N'Huyện Tân Phú Đông',N'Tan Phu Dong',N'Tan Phu Dong District',N'82'),
	 (N'829',N'Bến Tre',N'Thành phố Bến Tre',N'Ben Tre',N'Ben Tre City',N'83'),
	 (N'831',N'Châu Thành',N'Huyện Châu Thành',N'Chau Thanh',N'Chau Thanh District',N'83'),
	 (N'832',N'Chợ Lách',N'Huyện Chợ Lách',N'Cho Lach',N'Cho Lach District',N'83'),
	 (N'833',N'Mỏ Cày Nam',N'Huyện Mỏ Cày Nam',N'Mo Cay Nam',N'Mo Cay Nam District',N'83'),
	 (N'834',N'Giồng Trôm',N'Huyện Giồng Trôm',N'Giong Trom',N'Giong Trom District',N'83');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'835',N'Bình Đại',N'Huyện Bình Đại',N'Binh Dai',N'Binh Dai District',N'83'),
	 (N'836',N'Ba Tri',N'Huyện Ba Tri',N'Ba Tri',N'Ba Tri District',N'83'),
	 (N'837',N'Thạnh Phú',N'Huyện Thạnh Phú',N'Thanh Phu',N'Thanh Phu District',N'83'),
	 (N'838',N'Mỏ Cày Bắc',N'Huyện Mỏ Cày Bắc',N'Mo Cay Bac',N'Mo Cay Bac District',N'83'),
	 (N'842',N'Trà Vinh',N'Thành phố Trà Vinh',N'Tra Vinh',N'Tra Vinh City',N'84'),
	 (N'844',N'Càng Long',N'Huyện Càng Long',N'Cang Long',N'Cang Long District',N'84'),
	 (N'845',N'Cầu Kè',N'Huyện Cầu Kè',N'Cau Ke',N'Cau Ke District',N'84'),
	 (N'846',N'Tiểu Cần',N'Huyện Tiểu Cần',N'Tieu Can',N'Tieu Can District',N'84'),
	 (N'847',N'Châu Thành',N'Huyện Châu Thành',N'Chau Thanh',N'Chau Thanh District',N'84'),
	 (N'848',N'Cầu Ngang',N'Huyện Cầu Ngang',N'Cau Ngang',N'Cau Ngang District',N'84');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'849',N'Trà Cú',N'Huyện Trà Cú',N'Tra Cu',N'Tra Cu District',N'84'),
	 (N'850',N'Duyên Hải',N'Huyện Duyên Hải',N'Duyen Hai',N'Duyen Hai District',N'84'),
	 (N'851',N'Duyên Hải',N'Thị xã Duyên Hải',N'Duyen Hai',N'Duyen Hai Town',N'84'),
	 (N'855',N'Vĩnh Long',N'Thành phố Vĩnh Long',N'Vinh Long',N'Vinh Long City',N'86'),
	 (N'857',N'Long Hồ',N'Huyện Long Hồ',N'Long Ho',N'Long Ho District',N'86'),
	 (N'858',N'Mang Thít',N'Huyện Mang Thít',N'Mang Thit',N'Mang Thit District',N'86'),
	 (N'859',N'Vũng Liêm',N'Huyện Vũng Liêm',N'Vung Liem',N'Vung Liem District',N'86'),
	 (N'860',N'Tam Bình',N'Huyện Tam Bình',N'Tam Binh',N'Tam Binh District',N'86'),
	 (N'861',N'Bình Minh',N'Thị xã Bình Minh',N'Binh Minh',N'Binh Minh Town',N'86'),
	 (N'862',N'Trà Ôn',N'Huyện Trà Ôn',N'Tra On',N'Tra On District',N'86');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'863',N'Bình Tân',N'Huyện Bình Tân',N'Binh Tan',N'Binh Tan District',N'86'),
	 (N'866',N'Cao Lãnh',N'Thành phố Cao Lãnh',N'Cao Lanh',N'Cao Lanh City',N'87'),
	 (N'867',N'Sa Đéc',N'Thành phố Sa Đéc',N'Sa Dec',N'Sa Dec City',N'87'),
	 (N'868',N'Hồng Ngự',N'Thành phố Hồng Ngự',N'Hong Ngu',N'Hong Ngu City',N'87'),
	 (N'869',N'Tân Hồng',N'Huyện Tân Hồng',N'Tan Hong',N'Tan Hong District',N'87'),
	 (N'870',N'Hồng Ngự',N'Huyện Hồng Ngự',N'Hong Ngu',N'Hong Ngu District',N'87'),
	 (N'871',N'Tam Nông',N'Huyện Tam Nông',N'Tam Nong',N'Tam Nong District',N'87'),
	 (N'872',N'Tháp Mười',N'Huyện Tháp Mười',N'Thap Muoi',N'Thap Muoi District',N'87'),
	 (N'873',N'Cao Lãnh',N'Huyện Cao Lãnh',N'Cao Lanh',N'Cao Lanh District',N'87'),
	 (N'874',N'Thanh Bình',N'Huyện Thanh Bình',N'Thanh Binh',N'Thanh Binh District',N'87');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'875',N'Lấp Vò',N'Huyện Lấp Vò',N'Lap Vo',N'Lap Vo District',N'87'),
	 (N'876',N'Lai Vung',N'Huyện Lai Vung',N'Lai Vung',N'Lai Vung District',N'87'),
	 (N'877',N'Châu Thành',N'Huyện Châu Thành',N'Chau Thanh',N'Chau Thanh District',N'87'),
	 (N'883',N'Long Xuyên',N'Thành phố Long Xuyên',N'Long Xuyen',N'Long Xuyen City',N'89'),
	 (N'884',N'Châu Đốc',N'Thành phố Châu Đốc',N'Chau Doc',N'Chau Doc City',N'89'),
	 (N'886',N'An Phú',N'Huyện An Phú',N'An Phu',N'An Phu District',N'89'),
	 (N'887',N'Tân Châu',N'Thị xã Tân Châu',N'Tan Chau',N'Tan Chau Town',N'89'),
	 (N'888',N'Phú Tân',N'Huyện Phú Tân',N'Phu Tan',N'Phu Tan District',N'89'),
	 (N'889',N'Châu Phú',N'Huyện Châu Phú',N'Chau Phu',N'Chau Phu District',N'89'),
	 (N'890',N'Tịnh Biên',N'Thị xã Tịnh Biên',N'Tinh Bien',N'Tinh Bien Town',N'89');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'891',N'Tri Tôn',N'Huyện Tri Tôn',N'Tri Ton',N'Tri Ton District',N'89'),
	 (N'892',N'Châu Thành',N'Huyện Châu Thành',N'Chau Thanh',N'Chau Thanh District',N'89'),
	 (N'893',N'Chợ Mới',N'Huyện Chợ Mới',N'Cho Moi',N'Cho Moi District',N'89'),
	 (N'894',N'Thoại Sơn',N'Huyện Thoại Sơn',N'Thoai Son',N'Thoai Son District',N'89'),
	 (N'899',N'Rạch Giá',N'Thành phố Rạch Giá',N'Rach Gia',N'Rach Gia City',N'91'),
	 (N'900',N'Hà Tiên',N'Thành phố Hà Tiên',N'Ha Tien',N'Ha Tien City',N'91'),
	 (N'902',N'Kiên Lương',N'Huyện Kiên Lương',N'Kien Luong',N'Kien Luong District',N'91'),
	 (N'903',N'Hòn Đất',N'Huyện Hòn Đất',N'Hon Dat',N'Hon Dat District',N'91'),
	 (N'904',N'Tân Hiệp',N'Huyện Tân Hiệp',N'Tan Hiep',N'Tan Hiep District',N'91'),
	 (N'905',N'Châu Thành',N'Huyện Châu Thành',N'Chau Thanh',N'Chau Thanh District',N'91');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'906',N'Giồng Riềng',N'Huyện Giồng Riềng',N'Giong Rieng',N'Giong Rieng District',N'91'),
	 (N'907',N'Gò Quao',N'Huyện Gò Quao',N'Go Quao',N'Go Quao District',N'91'),
	 (N'908',N'An Biên',N'Huyện An Biên',N'An Bien',N'An Bien District',N'91'),
	 (N'909',N'An Minh',N'Huyện An Minh',N'An Minh',N'An Minh District',N'91'),
	 (N'910',N'Vĩnh Thuận',N'Huyện Vĩnh Thuận',N'Vinh Thuan',N'Vinh Thuan District',N'91'),
	 (N'911',N'Phú Quốc',N'Thành phố Phú Quốc',N'Phu Quoc',N'Phu Quoc City',N'91'),
	 (N'912',N'Kiên Hải',N'Huyện Kiên Hải',N'Kien Hai',N'Kien Hai District',N'91'),
	 (N'913',N'U Minh Thượng',N'Huyện U Minh Thượng',N'U Minh Thuong',N'U Minh Thuong District',N'91'),
	 (N'914',N'Giang Thành',N'Huyện Giang Thành',N'Giang Thanh',N'Giang Thanh District',N'91'),
	 (N'916',N'Ninh Kiều',N'Quận Ninh Kiều',N'Ninh Kieu',N'Ninh Kieu District',N'92');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'917',N'Ô Môn',N'Quận Ô Môn',N'O Mon',N'O Mon District',N'92'),
	 (N'918',N'Bình Thuỷ',N'Quận Bình Thuỷ',N'Binh Thuy',N'Binh Thuy District',N'92'),
	 (N'919',N'Cái Răng',N'Quận Cái Răng',N'Cai Rang',N'Cai Rang District',N'92'),
	 (N'923',N'Thốt Nốt',N'Quận Thốt Nốt',N'Thot Not',N'Thot Not District',N'92'),
	 (N'924',N'Vĩnh Thạnh',N'Huyện Vĩnh Thạnh',N'Vinh Thanh',N'Vinh Thanh District',N'92'),
	 (N'925',N'Cờ Đỏ',N'Huyện Cờ Đỏ',N'Co Do',N'Co Do District',N'92'),
	 (N'926',N'Phong Điền',N'Huyện Phong Điền',N'Phong Dien',N'Phong Dien District',N'92'),
	 (N'927',N'Thới Lai',N'Huyện Thới Lai',N'Thoi Lai',N'Thoi Lai District',N'92'),
	 (N'930',N'Vị Thanh',N'Thành phố Vị Thanh',N'Vi Thanh',N'Vi Thanh City',N'93'),
	 (N'931',N'Ngã Bảy',N'Thành phố Ngã Bảy',N'Nga Bay',N'Nga Bay City',N'93');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'932',N'Châu Thành A',N'Huyện Châu Thành A',N'Chau Thanh A',N'Chau Thanh A District',N'93'),
	 (N'933',N'Châu Thành',N'Huyện Châu Thành',N'Chau Thanh',N'Chau Thanh District',N'93'),
	 (N'934',N'Phụng Hiệp',N'Huyện Phụng Hiệp',N'Phung Hiep',N'Phung Hiep District',N'93'),
	 (N'935',N'Vị Thuỷ',N'Huyện Vị Thuỷ',N'Vi Thuy',N'Vi Thuy District',N'93'),
	 (N'936',N'Long Mỹ',N'Huyện Long Mỹ',N'Long My',N'Long My District',N'93'),
	 (N'937',N'Long Mỹ',N'Thị xã Long Mỹ',N'Long My',N'Long My Town',N'93'),
	 (N'941',N'Sóc Trăng',N'Thành phố Sóc Trăng',N'Soc Trang',N'Soc Trang City',N'94'),
	 (N'942',N'Châu Thành',N'Huyện Châu Thành',N'Chau Thanh',N'Chau Thanh District',N'94'),
	 (N'943',N'Kế Sách',N'Huyện Kế Sách',N'Ke Sach',N'Ke Sach District',N'94'),
	 (N'944',N'Mỹ Tú',N'Huyện Mỹ Tú',N'My Tu',N'My Tu District',N'94');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'945',N'Cù Lao Dung',N'Huyện Cù Lao Dung',N'Cu Lao Dung',N'Cu Lao Dung District',N'94'),
	 (N'946',N'Long Phú',N'Huyện Long Phú',N'Long Phu',N'Long Phu District',N'94'),
	 (N'947',N'Mỹ Xuyên',N'Huyện Mỹ Xuyên',N'My Xuyen',N'My Xuyen District',N'94'),
	 (N'948',N'Ngã Năm',N'Thị xã Ngã Năm',N'Nga Nam',N'Nga Nam Town',N'94'),
	 (N'949',N'Thạnh Trị',N'Huyện Thạnh Trị',N'Thanh Tri',N'Thanh Tri District',N'94'),
	 (N'950',N'Vĩnh Châu',N'Thị xã Vĩnh Châu',N'Vinh Chau',N'Vinh Chau Town',N'94'),
	 (N'951',N'Trần Đề',N'Huyện Trần Đề',N'Tran De',N'Tran De District',N'94'),
	 (N'954',N'Bạc Liêu',N'Thành phố Bạc Liêu',N'Bac Lieu',N'Bac Lieu City',N'95'),
	 (N'956',N'Hồng Dân',N'Huyện Hồng Dân',N'Hong Dan',N'Hong Dan District',N'95'),
	 (N'957',N'Phước Long',N'Huyện Phước Long',N'Phuoc Long',N'Phuoc Long District',N'95');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'958',N'Vĩnh Lợi',N'Huyện Vĩnh Lợi',N'Vinh Loi',N'Vinh Loi District',N'95'),
	 (N'959',N'Giá Rai',N'Thị xã Giá Rai',N'Gia Rai',N'Gia Rai Town',N'95'),
	 (N'960',N'Đông Hải',N'Huyện Đông Hải',N'Dong Hai',N'Dong Hai District',N'95'),
	 (N'961',N'Hoà Bình',N'Huyện Hoà Bình',N'Hoa Binh',N'Hoa Binh District',N'95'),
	 (N'964',N'Cà Mau',N'Thành phố Cà Mau',N'Ca Mau',N'Ca Mau City',N'96'),
	 (N'966',N'U Minh',N'Huyện U Minh',N'U Minh',N'U Minh District',N'96'),
	 (N'967',N'Thới Bình',N'Huyện Thới Bình',N'Thoi Binh',N'Thoi Binh District',N'96'),
	 (N'968',N'Trần Văn Thời',N'Huyện Trần Văn Thời',N'Tran Van Thoi',N'Tran Van Thoi District',N'96'),
	 (N'969',N'Cái Nước',N'Huyện Cái Nước',N'Cai Nuoc',N'Cai Nuoc District',N'96'),
	 (N'970',N'Đầm Dơi',N'Huyện Đầm Dơi',N'Dam Doi',N'Dam Doi District',N'96');
INSERT INTO Add_Districts (Id,Name,FullName,NameEN,FullNameEN,ProvinceId) VALUES
	 (N'971',N'Năm Căn',N'Huyện Năm Căn',N'Nam Can',N'Nam Can District',N'96'),
	 (N'972',N'Phú Tân',N'Huyện Phú Tân',N'Phu Tan',N'Phu Tan District',N'96'),
	 (N'973',N'Ngọc Hiển',N'Huyện Ngọc Hiển',N'Ngoc Hien',N'Ngoc Hien District',N'96');
